### ISSUE TITLE
Impossibile to compile with the latest bentel_kyo32.h

### ISSUE THREAD

**Issue by brembygit** [lorenzo-deluca/espkyogate#18]
Hi, 

with ESPHome  v2022.3.1 and latest  bentel_kyo32.h i still see the issue.

/config/esphome/bentel-control.yaml: In lambda function:
/config/esphome/bentel-control.yaml:37:16: error: 'class Bentel_Kyo32' has no member named 'zona_1'
         kyo32->zona_1,

/config/esphome/bentel-control.yaml:189:16: error: 'class Bentel_Kyo32' has no member named 'stato_uscita_8'
         kyo32->stato_uscita_8,
                ^
/config/esphome/bentel-control.yaml:206:9: error: could not convert '{<expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, kyo32->Bentel_Kyo32::kyo_comunication, kyo32->Bentel_Kyo32::stato_sirena, kyo32->Bentel_Kyo32::warn_mancanza_rete, kyo32->Bentel_Kyo32::warn_scomparsa_bpi, kyo32->Bentel_Kyo32::warn_fusibile, kyo32->Bentel_Kyo32::warn_batteria_bassa, kyo32->Bentel_Kyo32::warn_guasto_linea_telefonica, kyo32->Bentel_Kyo32::warn_codici_default, kyo32->Bentel_Kyo32::warn_wireless, kyo32->Bentel_Kyo32::sabotaggio_zona, kyo32->Bentel_Kyo32::sabotaggio_sistema, kyo32->Bentel_Kyo32::sabotaggio_bpi, kyo32->Bentel_Kyo32::sabotaggio_chiave_falsa, kyo32->Bentel_Kyo32::sabotaggio_jam, kyo32->Bentel_Kyo32::sabotaggio_wireless}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::binary_sensor::BinarySensor*>'
         };
         ^
Archiving /data/bentel-control/.pioenvs/bentel-control/libFrameworkArduinoVariant.a
Compiling /data/bentel-control/.pioenvs/bentel-control/FrameworkArduino/Esp.cpp.o
*** [/data/bentel-control/.pioenvs/bentel-control/src/main.cpp.o] Error 1

**Comment by lorenzo-deluca** [comment]
Have you check the new yaml configuration example?
Now zones are now pointed as arrays: `return {
        kyo32->kyo_comunication, &kyo32->zona[0], &kyo32->zona[1],&kyo32->zona[2], &kyo32->zona[3]};` etc..
