### ISSUE TITLE
Dispositivo non disponibile

### ISSUE THREAD

**Issue by manuele84** [lorenzo-deluca/espkyogate#2]
Complimenti per il progetto lo aspettavo da tanto che qualcuno implementasse il componente. Ho eseguito tutta la procedura come da guida su un d1 mini, pero in maniera random tutte l'entità perdono la connessione per qualche secondo su home assistant e diventano non disponibili.
Ho riscontrato anche che il sensore mancanza rete e lo stato sirena sono invertiti.

In fase di compilazione riscontro questo warning.
<img width="791" alt="errore compilazione" src="https://user-images.githubusercontent.com/63157208/140988551-bcc85932-1730-4a1d-ac90-abae8297cb4c.PNG">

**Comment by lcavalli** [comment]
Anche a me è capitato durante lo sviluppo del codice. Ero al piano di sotto e l'access point configurato nel firmware era al piano di sopra. Il segnale era piuttosto debole e la connessione spesso cadeva, riagganciandosi poco dopo. Tieni conto anche della dimensione dell'antennina del modulo ESP8266, non proprio generosa. Io poi ho messo tutto in una scatoletta a sua volta dentro il box della centralina dell'allarme e penso che un po' attenuino il segnale.

I warning in compilazione sono, appunto, warning. Possono essere rimossi :smile:

**Comment by lorenzo-deluca** [comment]
Ciao ragazzi,
i warning prima o poi li sistemerò... comunque non incidono sul funzionamento del firmware.

Credo anche io che il problema sia dovuto al WiFi, effettivamente non "tira" molto il wifi di quel modulo.
Direi che hai due possibilità, o cerchi di avvicinare l'access point alla centrale dell'allarme oppure cambi modulo e usi un modulo tipo il D1 mini Pro che ha un'antenna wifi esterna.

**Comment by manuele84** [comment]
Grazie per i consigli, ho installato un repiter vicino la centrale e fin ora non ha dato più entità non disponibili.

Per caso avete riscontrato anche voi che  il sensore di mancanza rete è invertito con lo stato sirena?

**Comment by lcavalli** [comment]
Nello yaml di esempio non mi pare:
```yaml
      return { 
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
[...]
    binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
```
Non li hai invertiti nella tua configurazione (l'ordine dei valori ritornati e l'ordine dei sensori definiti è importante)?

**Comment by lorenzo-deluca** [comment]
Prova a verificare la configurazione come dice @lcavalli .
Se hai ancora problemi faccio un controllo, però ricordo che durante lo sviluppo avevo provato tutti i segnali e mi sembrava tutto ok. Fammi sapere 😉

**Comment by Ropese** [comment]
Progetto stupendo a giorni sostituisco la norma 8 con una kyo e testo il tutto. L’unica cosa che non trovo e dove settare i nomi delle zone. Grazie

**Comment by lorenzo-deluca** [comment]
ok, ottimo!
Intanto chiudo questa segnalazione ;)
