### ISSUE TITLE
funziona con absoluta?

### ISSUE THREAD

**Issue by ilgio** [lorenzo-deluca/espkyogate#20]
sto cercando disperatamente una soluzione per bentel absoluta
questa guida potrebbe andar bene anche per absoluta?

**Comment by lorenzo-deluca** [comment]
Ciao, me lo chiedono in tanti ma se non ho capito male con Absoluta è tutto molto più facile perché è già in rete.

**Comment by ilgio** [comment]
quindi non funziona?
non è possibile adattarlo?
