### ISSUE TITLE
kyo 8M

### ISSUE THREAD

**Issue by bogdanabaza** [lorenzo-deluca/espkyogate#21]
Hi Lorenzo,
Thank you for your work on kyo integration on HA.
I have a kyo8M. I'm trying to connect it with esp32 and HA.
I made all the hardware setup. Now I have troubles on serial communication. I tried to use your bentel_kyo32.h but I it didn't wok.
The logs look like here:
![image](https://user-images.githubusercontent.com/64099623/173807754-7d2086fb-06e9-4bb6-980a-181084983610.png)

Do you have any suggestion or hint please?
Tks,

**Comment by lorenzo-deluca** [comment]
Hello ;)
there might be something to fix to handle the messages from Kyo 8.
Anyway, however, it seems to be unresponsive on the serial port.
Are the pins you have configured correct? have you tried reversing TX and RX yet?
The serial only works when you are not PROGRAMMING MODE.

Let me know! thanks ;)

**Comment by bogdanabaza** [comment]
Yes, I reverse the TX and RX and no result. 
The programming mode is not activated.
Here is the pins:
![image](https://user-images.githubusercontent.com/64099623/173825001-9dab6594-fcd6-442f-93d7-d8a171f11b24.png)
The response is the same:
![image](https://user-images.githubusercontent.com/64099623/173825073-03e8d065-995e-42cd-9c88-a95edcc71992.png)

**Comment by lorenzo-deluca** [comment]
So if it's okay on the serial side probably the Kyo 8 is not responding to that message, I tested this firmware only on Bentel Kyo32G..
If you feel like analyzing the protocol and you have Bentel software you can connect to it and see with software like serialmon what hexadecimal messages it accepts from Bentel software. it's not super easy but you can have fun ;)

**Comment by bogdanabaza** [comment]
Ok. 
I have Bentel software - Kyo Unit - and it works woth it. Before to look at the protocol in hexa I'll try to change the serial converter to be sure that is not from it.
Thank you!

**Comment by lorenzo-deluca** [comment]
Hi @bogdanabaza, if you want to retry with the help of other users who have the Kyo8 unit, I worked on a version that should work.
For now, you can find it in this branch:  https://github.com/lorenzo-deluca/espkyogate/tree/hotfix/handle-kyo8

If you want to try it out and let me know how it goes.
