### ISSUE TITLE
bentel_kyo32.h - v1.3.0 - doesn't work with more than 1 Zone, Exit or Area

### ISSUE THREAD

**Issue by brembygit** [lorenzo-deluca/espkyogate#24]
I tried to test the latest version; 
but it breaks the ESP :(

as soon I add an additional entry (exit, zone, etc) I can’t access the ESP with esphome. 
I can ping it, but I can’t connect any more

any change that you can test it on your side?

**Comment by brembygit** [comment]
Nevermind, I started from scratch and it works

**Comment by lorenzo-deluca** [comment]
ok, great ;)
