### ISSUE TITLE
Aggiorna documentazione

### ISSUE THREAD

**Issue by john8329** [lorenzo-deluca/espkyogate#38]
Buondì, e intanto grazie per questa integrazione. Sto cercando da qualche ora di capire come strutturare il file di configurazione e le zone, e noto che diverse parti del README sembrano obsolete, in particolare (per ora):

* ~~La configurazione del tipo dispositivo sembra non essere accettata, e non sono presenti icone in HASS. Come bisogna fare?~~ niente ora l'ha preso, svista mia
* Non è chiaro come vanno mappate le zone e le aree, l'esempio non corrisponde con il file yaml aggiornato
  * Nel template in C vanno mappate le sole zone programmate seguendo l'indice immagino. Quindi se la zona 5 non è definita va rimosso `&kyo32→zona[4]`, corretto?
* I nomi ad hoc delle zone aiutano a identificare i sensori, meglio dare un esempio (tipo "Porta Ingresso" ecc...)
* Il file `secrets.yaml` ha una chiave errata (dovrebbe essere `ha_password` dal file yaml), anche se in realtà il nome è corretto. La password è deprecata a favore della API encryption key, quindi andrebbe aggiornato il file yaml con la chiave corretta sotto `api.encryption.key`. Da documentare che si può ottenere da esphome.io/components/api.html
* Bisognerebbe chiarire che i log sono visibili solo via OTA per via del bug che ho visto risolto riguardante il conflitto con la porta seriale
* Trovo comodo se viene specificato un `friendly_name` sotto `esphome` in modo che venga visualizzato meglio su HA
* Andrebbe spiegato quando usare lo switch "safe mode"
* Per chi non è pratico di esphome, forse è utile dare un link alla [interfaccia web](https://web.esphome.io)

Penso che per aiutare utenti alle prime armi o senza una laurea in ingegneria, sia opportuno raffinare il README.

...e nonostante tutto il resto era scritto bene e sono riuscito a farlo funzionare! Devo dire che è una f.. pazzesca, e se vedo che è stabile, altro che caffè. 
Grazie!!

**Comment by lorenzo-deluca** [comment]
Ciao, grazie a te, allora aspetto la birra! 😁

Per quanto riguarda la documentazione si, hai ragione, considera che ero partito con un firmware from scratch che comunicava via MQTT prima a Domoticz e poi ad Home Assistant.
Su suggerimento di molti utenti ho migrato a ESPHome ormai un paio di anni fa e la documentazione si riferiva alla versione di ESPHome di allora.

In realtà, come hai visto, funziona pure con l'ultima, bisogna sistemare qualche attributo del file yaml che hanno deprecato ultima a te.

Effettivamente è un po' per utenti esperti, però guarda, io sono in vacanza e rientro la prossima settimana.
Se vuoi puoi fare un fork del mio README, modificarlo come ritieni possa essere meglio comprensibile all'utente meno avvezzo e quando rientro faccio un merge.

Avevo anche in canna altre modifiche che mi avevano chiesto altri utenti, come il reset delle chiamate del combinatore telefonico e il test della sirena, che vorrei fare così da poter sfruttare le sirene anche per automazioni Home Assistant 😉

A presto 😉

**Comment by john8329** [comment]
Mi sembra onesto, vedo di fare qualche modifica nei prossimi giorni e creare il pull request. Per ora la centrale sembra stabile, a parte qualche disconnessione che devo ancora indagare.
Sicuramente passare a ESPHome è stata una mossa vincente. Sembra fatto piuttosto bene.

Buon rientro

**Comment by lorenzo-deluca** [comment]
> Mi sembra onesto, vedo di fare qualche modifica nei prossimi giorni e creare il pull request. Per ora la centrale sembra stabile, a parte qualche disconnessione che devo ancora indagare.
> 
> Sicuramente passare a ESPHome è stata una mossa vincente. Sembra fatto piuttosto bene.
> 
> 
> 
> Buon rientro

Grazie! 🙂
Per quanto riguarda le disconnessioni sembra che si risolva con un hardware leggermente più performante del Wemos D1 che consiglio di usare, basta fare l'upgrade ad un ESP32 qualsiasi da pochi euro.
Io personalmente ne ho installate due su Wemos D1 da diversi anni e non rilevo problemi di disconnessione ma c'è da dire che in tutte e due le centrali l'access point è praticamente a mezzo metro dalla centrale.

Fammi sapere come va 😉

**Comment by john8329** [comment]
Ecco il PR. Non riesci ad inviare la cassa di birre in quanto quel sito mi rifiuta la carta, proverò fra qualche giorno. 
https://github.com/lorenzo-deluca/espkyogate/pull/39
