### ISSUE TITLE
Component <unknow> took a long time...

### ISSUE THREAD

**Issue by brusarp** [lorenzo-deluca/espkyogate#4]
Hello,
although everything still seems to work correctly in the esphome logs, what is written in the attached screeshot appears to me ...
It's normal? How can I do to help you understand what it could be.
My device is a Wemos D1mini with a Kyo32G

![image](https://user-images.githubusercontent.com/14950532/143007053-f2fd0fa7-20a7-4ae7-b4a1-db8c6b4cd40a.png)

**Comment by lorenzo-deluca** [comment]
Hello,
yes, it's "normal" because the serial communication with Kyo32G take a little bit time...
I'm not so expert of ESPHome, I don't know if this can be parameterized.

**Comment by brusarp** [comment]
Oh, ok!
Understood... 👍🏻
