### ISSUE TITLE
Move `bentel-kyo` to `components/bentel-kyo`

### ISSUE THREAD

**Issue by ruimarinho** [lorenzo-deluca/espkyogate#40]
Hi @lorenzo-deluca,

In order to use the `external_components` directive of esphome, the git repository must follow a certain structure, as documented under https://esphome.io/components/external_components.html.

My recommend would be to move `bentel-kyo` to `components/`, as in:

```
components
├── bentel-kyo
│    └── bentel_kyo32.h
```

**Comment by lorenzo-deluca** [comment]
Hello @ruimarinho, moved,  thanks for recommendation 👍
