### ISSUE TITLE
Errore durante la compilazione

### ISSUE THREAD

**Issue by fabix683** [lorenzo-deluca/espkyogate#43]
Salve Lorenzo.
Sto provando a compilare il tuo progetto tramite ESPHOME

Durante la compilazione ricevo i seguenti messaggi d'errore.
Grazie

` - 
      ID exit_status_1 redefined! Check binary_sensor->0->binary_sensors->55->id.
      id: exit_status_1
      name: Stato Uscita 1
      disabled_by_default: False
    - 
      ID exit_status_1 redefined! Check binary_sensor->0->binary_sensors->55->id.
      id: exit_status_1
      name: Stato Uscita 1
      disabled_by_default: False
    - 
      ID exit_status_1 redefined! Check binary_sensor->0->binary_sensors->55->id.
      id: exit_status_1
      name: Stato Uscita 1
      disabled_by_default: False`

Di seguito il log completo

[logs_esphome-web-53c388_compile.txt](https://github.com/lorenzo-deluca/espkyogate/files/13197411/logs_esphome-web-53c388_compile.txt)

**Comment by lorenzo-deluca** [comment]
Ciao @fabix683,
a prima vista sembra che hai duplicato "exit_status_1"
Fai un check, eventualmente prova a postare l'intero yaml (senza password, ovviamente).

Fammi sapere come va ;)

**Comment by fabix683** [comment]
Grazie per la risposta. 
Ho usato come file di configurazione quello allegato al progetto ed in effetti ho visto che alla fine "exit_status_1" è duplicato 4 volte
Ho corretto questo errore ma ancora qualcosa non va, ora ricevo 

Compiling .pioenvs/espkyogatebox/libfe8/ESPAsyncTCP-esphome/AsyncPrinter.cpp.o
/config/esphome/esphome-web-53c388.yaml: In lambda function:
/config/esphome/esphome-web-53c388.yaml:115:56: error: expected primary-expression before '.' token
  115 |         &kyo32->inserimento_parziale_ritardo_0_area[3],.
      |                                                        ^
/config/esphome/esphome-web-53c388.yaml:117:9: error: expected unqualified-id before '&' token
  117 |         &kyo32->disinserita_area[0],

Allego file completo del log e file Yaml usato 
[logs_esphome-web-53c388_compile (1).txt](https://github.com/lorenzo-deluca/espkyogate/files/13197690/logs_esphome-web-53c388_compile.1.txt)

**Comment by lorenzo-deluca** [comment]
Linea 115 del file yaml, c'è un "." di troppo ;)
