### ISSUE TITLE
binary sensor "platform: custom" probably deprecated unable to build

### ISSUE THREAD

**Issue by joyride1176** [lorenzo-deluca/espkyogate#44]
Hi,

I'm trying to build the image for ESP board but probably the yaml configuration isn't supported anymore by new esphome version 2023.12.1

Documentation:
https://esphome.io/components/binary_sensor/custom.html

"Warning
Custom components are deprecated, not recommended for new configurations and will be removed from ESPHome in a future release. Please look at creating a real ESPHome component and “importing” it into your configuration with [External Components](https://esphome.io/components/external_components)."

Error appear with default yaml file proposed by you with minor config:

Error:

----------------------------------------------------------------
INFO ESPHome 2023.12.1
INFO Reading configuration /config/esphome/test.yaml...
Failed config

binary_sensor.custom: [source <unicode string>:45]
  platform: custom
----------------------------------------------------------------

Any suggestion?

YAML full config
`esphome:
  name: test
  friendly_name: Test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oytieDmV1TM/VhzQa+j1MzWY9/6+mDxHV/cooCm78cY="

ota:
  password: "e1bb229aced5b43622cdea640593ffde"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "NFe76qjMlqax"

captive_portal:

  
uart:
  id: uart_bus
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  
switch:
  - platform: safe_mode
    name: "ESPKyoGate (Safe Mode)"

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_mancanza_rete,
        kyo32->sabotaggio_zona, 
        kyo32->sabotaggio_sistema,
        kyo32->warn_scomparsa_bpi,
        kyo32->warn_fusibile,
        kyo32->warn_batteria_bassa,
        kyo32->warn_guasto_linea_telefonica,
        kyo32->warn_codici_default,
        kyo32->warn_wireless,
        kyo32->sabotaggio_bpi,
        kyo32->sabotaggio_jam,
        kyo32->sabotaggio_wireless,
        kyo32->sabotaggio_chiave_falsa,

        &kyo32->zona[0],
        &kyo32->zona[1],
        &kyo32->zona[2],
        &kyo32->zona[3],

        &kyo32->zona_sabotaggio[0],
        &kyo32->zona_sabotaggio[1],
        &kyo32->zona_sabotaggio[2],
        &kyo32->zona_sabotaggio[3],

        &kyo32->zona_esclusa[0],
        &kyo32->zona_esclusa[1],
        &kyo32->zona_esclusa[2],
        &kyo32->zona_esclusa[3],

        &kyo32->memoria_allarme_zona[0],
        &kyo32->memoria_allarme_zona[1],
        &kyo32->memoria_allarme_zona[2],
        &kyo32->memoria_allarme_zona[3],

        &kyo32->memoria_sabotaggio_zona[0],
        &kyo32->memoria_sabotaggio_zona[1],
        &kyo32->memoria_sabotaggio_zona[2],
        &kyo32->memoria_sabotaggio_zona[3],

        &kyo32->allarme_area[0],
        &kyo32->allarme_area[1],
        &kyo32->allarme_area[2],
        &kyo32->allarme_area[3],

        &kyo32->inserimento_totale_area[0],
        &kyo32->inserimento_totale_area[1],
        &kyo32->inserimento_totale_area[2],
        &kyo32->inserimento_totale_area[3],

        &kyo32->inserimento_parziale_area[0],
        &kyo32->inserimento_parziale_area[1],
        &kyo32->inserimento_parziale_area[2],
        &kyo32->inserimento_parziale_area[3],

        &kyo32->inserimento_parziale_ritardo_0_area[0],
        &kyo32->inserimento_parziale_ritardo_0_area[1],
        &kyo32->inserimento_parziale_ritardo_0_area[2],
        &kyo32->inserimento_parziale_ritardo_0_area[3],

        &kyo32->disinserita_area[0],
        &kyo32->disinserita_area[1],
        &kyo32->disinserita_area[2],
        &kyo32->disinserita_area[3],

        &kyo32->stato_uscita[0],
        &kyo32->stato_uscita[1],
        &kyo32->stato_uscita[2],
        &kyo32->stato_uscita[3]
      };
    binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
      - id: warn_mancanza_rete
        name: "Mancanza Rete"
      - id: sabotaggio_zona
        name: "Sabotaggio Zona"
      - id: sabotaggio_sistema
        name: "Sabotaggio Sistema"
      - id: warn_scomparsa_bpi
        name: "Scomparsa BPI"
      - id: warn_fusibile
        name: "Fusibile"
      - id: warn_batteria_bassa
        name: "Batteria Bassa"
      - id: warn_guasto_linea_telefonica
        name: "Guasto Linea Telefonica"
      - id: warn_codici_default
        name: "Codici Default"
      - id: warn_wireless
        name: "Wireless"
      - id: sabotaggio_bpi
        name: "Sabotaggio BPI"
      - id: sabotaggio_jam
        name: "Sabotaggio Jam"
      - id: sabotaggio_wireless
        name: "Sabotaggio wireless"
      - id: sabotaggio_chiave_falsa
        name: "Sabotaggio Chiave Falsa"

      - id: zona_1
        name: "Sensore DT Taverna"
        device_class: "motion"
      - id: zone_2
        name: "Finestra Taverna"
        device_class: "window"
      - id: zone_3
        name: "Sensore DT Garage"
        device_class: "motion"
      - id: zone_4
        name: "Scuretto Finestra Lavanderia"
        device_class: "window"

      - id: zona_1_sabotaggio
        name: "Sabot. Sensore DT Taverna"
      - id: zona_2_sabotaggio
        name: "Sabot. Finestra Taverna"
      - id: zona_3_sabotaggio
        name: "Sabot. Sensore DT Garage"
      - id: zona_4_sabotaggio
        name: "Sabot. Scuretto Finestra Lavanderia"

      - id: excluded_zone_1
        name: "Escl. Sensore DT Taverna"
      - id: excluded_zone_2
        name: "Escl. Finestra Taverna"
      - id: excluded_zone_3
        name: "Escl. Sensore DT Garage"
      - id: excluded_zone_4
        name: "Escl. Scuretto Finestra Lavanderia"

      - id: alarm_memory_zone_1
        name: "Mem. Allarme Sensore DT Taverna"
      - id: alarm_memory_zone_2
        name: "Mem. Allarme Finestra Taverna"
      - id: alarm_memory_zone_3
        name: "Mem. Allarme Sensore DT Garage"
      - id: alarm_memory_zone_4
        name: "Mem. Allarme Scuretto Finestra Lavanderia"

      - id: sabotage_memory_zone_1
        name: "Mem. Sabotaggio Sensore DT Taverna"
      - id: sabotage_memory_zone_2
        name: "Mem. Sabotaggio Finestra Taverna"
      - id: sabotage_memory_zone_3
        name: "Mem. Sabotaggio Sensore DT Garage"
      - id: sabotage_memory_zone_4
        name: "Mem. Sabotaggio Scuretto Finestra Lavanderia"

      - id: alarm_area_1
        name: "Allarme Finestre"
      - id: alarm_area_2
        name: "Allarme Area 2"
      - id: alarm_area_3
        name: "Allarme Area 3"
      - id: alarm_area_4
        name: "Allarme Area Sensori Interni"

      - id: enabled_total_area_1
        name: "Ins. Totale Finestre"
      - id: enabled_total_area_2
        name: "Ins. Totale Porte"
      - id: enabled_total_area_3
        name: "Ins. Totale Sensori Giardino"
      - id: enabled_total_area_4
        name: "Ins. Totale Sensori Interni"

      - id: enabled_partial_area_1
        name: "Ins. Parziale Finestre"
      - id: enabled_partial_area_2
        name: "Ins. Parziale Porte"
      - id: enabled_partial_area_3
        name: "Ins. Parziale Sensori Giardino"
      - id: enabled_partial_area_4
        name: "Ins. Parziale Sensori Interni"        

      - id: enabled_partial_delay_0_area_1
        name: "Ins. Parziale Ritardo 0 Finestre"
      - id: enabled_partial_delay_0_area_2
        name: "Ins. Parziale Ritardo 0 Porte"
      - id: enabled_partial_delay_0_area_3
        name: "Ins. Parziale Ritardo 0 Sensori Giardino"
      - id: enabled_partial_delay_0_area_4
        name: "Ins. Parziale Ritardo 0 Sensori Interni"

      - id: disabled_area_1
        name: "Disins. Finestre"
      - id: disabled_area_2
        name: "Disins. Porte"
      - id: disabled_area_3
        name: "Disins. Sensori Giardino"
      - id: disabled_area_4
        name: "Disins. Sensori Interni"

      - id: exit_status_1
        name: "Stato Uscita 1"
      - id: exit_status_1
        name: "Stato Uscita 1"
      - id: exit_status_1
        name: "Stato Uscita 1"
      - id: exit_status_1
        name: "Stato Uscita 1" 
    `

Full log error:

`INFO ESPHome 2023.12.1
INFO Reading configuration /config/esphome/test.yaml...
Failed config

binary_sensor.custom: [source <unicode string>:45]
  platform: custom
  lambda: !lambda |-
    auto kyo32 = new Bentel_Kyo32(id(uart_bus));
    App.register_component(kyo32);
    return {
      kyo32->kyo_comunication,
      kyo32->stato_sirena,
      kyo32->warn_mancanza_rete,
      kyo32->sabotaggio_zona, 
      kyo32->sabotaggio_sistema,
      kyo32->warn_scomparsa_bpi,
      kyo32->warn_fusibile,
      kyo32->warn_batteria_bassa,
      kyo32->warn_guasto_linea_telefonica,
      kyo32->warn_codici_default,
      kyo32->warn_wireless,
      kyo32->sabotaggio_bpi,
      kyo32->sabotaggio_jam,
      kyo32->sabotaggio_wireless,
      kyo32->sabotaggio_chiave_falsa,
    
      &kyo32->zona[0],
      &kyo32->zona[1],
      &kyo32->zona[2],
      &kyo32->zona[3],
    
      &kyo32->zona_sabotaggio[0],
      &kyo32->zona_sabotaggio[1],
      &kyo32->zona_sabotaggio[2],
      &kyo32->zona_sabotaggio[3],
    
      &kyo32->zona_esclusa[0],
      &kyo32->zona_esclusa[1],
      &kyo32->zona_esclusa[2],
      &kyo32->zona_esclusa[3],
    
      &kyo32->memoria_allarme_zona[0],
      &kyo32->memoria_allarme_zona[1],
      &kyo32->memoria_allarme_zona[2],
      &kyo32->memoria_allarme_zona[3],
    
      &kyo32->memoria_sabotaggio_zona[0],
      &kyo32->memoria_sabotaggio_zona[1],
      &kyo32->memoria_sabotaggio_zona[2],
      &kyo32->memoria_sabotaggio_zona[3],
    
      &kyo32->allarme_area[0],
      &kyo32->allarme_area[1],
      &kyo32->allarme_area[2],
      &kyo32->allarme_area[3],
    
      &kyo32->inserimento_totale_area[0],
      &kyo32->inserimento_totale_area[1],
      &kyo32->inserimento_totale_area[2],
      &kyo32->inserimento_totale_area[3],
    
      &kyo32->inserimento_parziale_area[0],
      &kyo32->inserimento_parziale_area[1],
      &kyo32->inserimento_parziale_area[2],
      &kyo32->inserimento_parziale_area[3],
    
      &kyo32->inserimento_parziale_ritardo_0_area[0],
      &kyo32->inserimento_parziale_ritardo_0_area[1],
      &kyo32->inserimento_parziale_ritardo_0_area[2],
      &kyo32->inserimento_parziale_ritardo_0_area[3],
    
      &kyo32->disinserita_area[0],
      &kyo32->disinserita_area[1],
      &kyo32->disinserita_area[2],
      &kyo32->disinserita_area[3],
    
      &kyo32->stato_uscita[0],
      &kyo32->stato_uscita[1],
      &kyo32->stato_uscita[2],
      &kyo32->stato_uscita[3]
    };
  binary_sensors: 
    - id: kyo_comunication
      name: Comunicazione Centrale
      disabled_by_default: False
    - id: stato_sirena
      name: Stato Sirena
      disabled_by_default: False
    - id: warn_mancanza_rete
      name: Mancanza Rete
      disabled_by_default: False
    - id: sabotaggio_zona
      name: Sabotaggio Zona
      disabled_by_default: False
    - id: sabotaggio_sistema
      name: Sabotaggio Sistema
      disabled_by_default: False
    - id: warn_scomparsa_bpi
      name: Scomparsa BPI
      disabled_by_default: False
    - id: warn_fusibile
      name: Fusibile
      disabled_by_default: False
    - id: warn_batteria_bassa
      name: Batteria Bassa
      disabled_by_default: False
    - id: warn_guasto_linea_telefonica
      name: Guasto Linea Telefonica
      disabled_by_default: False
    - id: warn_codici_default
      name: Codici Default
      disabled_by_default: False
    - id: warn_wireless
      name: Wireless
      disabled_by_default: False
    - id: sabotaggio_bpi
      name: Sabotaggio BPI
      disabled_by_default: False
    - id: sabotaggio_jam
      name: Sabotaggio Jam
      disabled_by_default: False
    - id: sabotaggio_wireless
      name: Sabotaggio wireless
      disabled_by_default: False
    - id: sabotaggio_chiave_falsa
      name: Sabotaggio Chiave Falsa
      disabled_by_default: False
    - id: zona_1
      name: Sensore DT Taverna
      device_class: motion
      disabled_by_default: False
    - id: zone_2
      name: Finestra Taverna
      device_class: window
      disabled_by_default: False
    - id: zone_3
      name: Sensore DT Garage
      device_class: motion
      disabled_by_default: False
    - id: zone_4
      name: Scuretto Finestra Lavanderia
      device_class: window
      disabled_by_default: False
    - id: zona_1_sabotaggio
      name: Sabot. Sensore DT Taverna
      disabled_by_default: False
    - id: zona_2_sabotaggio
      name: Sabot. Finestra Taverna
      disabled_by_default: False
    - id: zona_3_sabotaggio
      name: Sabot. Sensore DT Garage
      disabled_by_default: False
    - id: zona_4_sabotaggio
      name: Sabot. Scuretto Finestra Lavanderia
      disabled_by_default: False
    - id: excluded_zone_1
      name: Escl. Sensore DT Taverna
      disabled_by_default: False
    - id: excluded_zone_2
      name: Escl. Finestra Taverna
      disabled_by_default: False
    - id: excluded_zone_3
      name: Escl. Sensore DT Garage
      disabled_by_default: False
    - id: excluded_zone_4
      name: Escl. Scuretto Finestra Lavanderia
      disabled_by_default: False
    - id: alarm_memory_zone_1
      name: Mem. Allarme Sensore DT Taverna
      disabled_by_default: False
    - id: alarm_memory_zone_2
      name: Mem. Allarme Finestra Taverna
      disabled_by_default: False
    - id: alarm_memory_zone_3
      name: Mem. Allarme Sensore DT Garage
      disabled_by_default: False
    - id: alarm_memory_zone_4
      name: Mem. Allarme Scuretto Finestra Lavanderia
      disabled_by_default: False
    - id: sabotage_memory_zone_1
      name: Mem. Sabotaggio Sensore DT Taverna
      disabled_by_default: False
    - id: sabotage_memory_zone_2
      name: Mem. Sabotaggio Finestra Taverna
      disabled_by_default: False
    - id: sabotage_memory_zone_3
      name: Mem. Sabotaggio Sensore DT Garage
      disabled_by_default: False
    - id: sabotage_memory_zone_4
      name: Mem. Sabotaggio Scuretto Finestra Lavanderia
      disabled_by_default: False
    - id: alarm_area_1
      name: Allarme Finestre
      disabled_by_default: False
    - id: alarm_area_2
      name: Allarme Area 2
      disabled_by_default: False
    - id: alarm_area_3
      name: Allarme Area 3
      disabled_by_default: False
    - id: alarm_area_4
      name: Allarme Area Sensori Interni
      disabled_by_default: False
    - id: enabled_total_area_1
      name: Ins. Totale Finestre
      disabled_by_default: False
    - id: enabled_total_area_2
      name: Ins. Totale Porte
      disabled_by_default: False
    - id: enabled_total_area_3
      name: Ins. Totale Sensori Giardino
      disabled_by_default: False
    - id: enabled_total_area_4
      name: Ins. Totale Sensori Interni
      disabled_by_default: False
    - id: enabled_partial_area_1
      name: Ins. Parziale Finestre
      disabled_by_default: False
    - id: enabled_partial_area_2
      name: Ins. Parziale Porte
      disabled_by_default: False
    - id: enabled_partial_area_3
      name: Ins. Parziale Sensori Giardino
      disabled_by_default: False
    - id: enabled_partial_area_4
      name: Ins. Parziale Sensori Interni
      disabled_by_default: False
    - id: enabled_partial_delay_0_area_1
      name: Ins. Parziale Ritardo 0 Finestre
      disabled_by_default: False
    - id: enabled_partial_delay_0_area_2
      name: Ins. Parziale Ritardo 0 Porte
      disabled_by_default: False
    - id: enabled_partial_delay_0_area_3
      name: Ins. Parziale Ritardo 0 Sensori Giardino
      disabled_by_default: False
    - id: enabled_partial_delay_0_area_4
      name: Ins. Parziale Ritardo 0 Sensori Interni
      disabled_by_default: False
    - id: disabled_area_1
      name: Disins. Finestre
      disabled_by_default: False
    - id: disabled_area_2
      name: Disins. Porte
      disabled_by_default: False
    - id: disabled_area_3
      name: Disins. Sensori Giardino
      disabled_by_default: False
    - id: disabled_area_4
      name: Disins. Sensori Interni
      disabled_by_default: False
    - id: exit_status_1
      name: Stato Uscita 1
      disabled_by_default: False
    - 
      ID exit_status_1 redefined! Check binary_sensor->0->binary_sensors->55->id.
      id: exit_status_1
      name: Stato Uscita 1
      disabled_by_default: False
    - 
      ID exit_status_1 redefined! Check binary_sensor->0->binary_sensors->55->id.
      id: exit_status_1
      name: Stato Uscita 1
      disabled_by_default: False
    - 
      ID exit_status_1 redefined! Check binary_sensor->0->binary_sensors->55->id.
      id: exit_status_1
      name: Stato Uscita 1
      disabled_by_default: False`

**Comment by lorenzo-deluca** [comment]
Hello, 
I saw the warning but it is only a warning, I recompiled everything with ESPHome 2023.12.3 and it works ;)
In your case the problem is clear, you have defined "exit_status_1" several times.

(for the next times if you want to post your configuration use the appropriate yaml identifier)

Happy Christmas :christmas_tree:
