### ISSUE TITLE
KYO8 ed attivazione allarme

### ISSUE THREAD

**Issue by pow3r77** [lorenzo-deluca/espkyogate#49]
Ciao Lorenzo,
complimenti per il lavoro, lo sto testando su una centrale KYO8
 Quando lancio il servizio per armare la zona 1 (unica zone nella mia centrale configurata) la zona si attiva correttamente ma partono anche le chiamate telefoniche di attivazione allarme. Stessa cosa quando disarmo con il service "disarm"

tutte le volte sento scattare un "doppio" relè e si attiva il compositore telefonico.

Hai qualche idea?

Grazie mille

**Comment by lorenzo-deluca** [comment]
Ciao, non ho mai avuto il compositore telefonico.. però è strano, nessuno mi ha mai segnalato questo problema.
Hai provato anche con l'abilitazione parziale?

**Comment by pow3r77** [comment]
In pratica attivando con la modalità 1 mi fa un "attivazione speciale" che dovrebbe corrispondere all'attivazione "antipanico"in affetto, motivo per il quale fa partire il combinatore

![image](https://github.com/lorenzo-deluca/espkyogate/assets/45035125/48b60a99-fac3-4c6d-ace1-4b5945e9a1c4)

Adesso provo altri tipi di attivazione

**Comment by pow3r77** [comment]
Allora, ho inviato ex-novo la configurazione e adesso funziona tutto. Ovviamente non trovo un nesso logico, ma non mi attiva in automatico le telefonate.
Ritieni ci sia un modo per chiamare anche il servizio di "cancella telefonate" ? Essendo una delle opzioni del menu quando si attiva il combinatore. Sarebbe molto utile per interrompere il "loop" delle chiamate

**Comment by pow3r77** [comment]
Giusto per darti un feedback generale, su KYO8 probabilmente alcuni voci non sono allineate, quando attivo allarme totale area 1, mi si attiva il sensore " - id: disabled_area_1"
Se faccio un attivazione della medesima area parziale non si attiva invece nessuno dei sensori creati in HA.
Ritieni ci sia possibilità di allinearli?
Grazie infinite della disponibilità, qualora non avessi tempo e voglia di seguire le mie indicazioni comprendo ;)
Grazie e buona serata

**Comment by lorenzo-deluca** [comment]
Ciao, grazie del feedback.
Penso possa essere un problema di configurazione yaml perché mi hanno scritto diversi utenti con Kyo 8G, 8M e 8W che non hanno riscontrato problemi.
Puoi postare qui la tua configurazione yaml (senza password, ovviamente)?

**Comment by pow3r77** [comment]
esphome:
  name: espkyogatebox
  friendly_name: Allarme Casa
  comment: Alarm System Serial to HA controller
  includes:
    - bentel-kyo/bentel_kyo32.h

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: "uJxOXuy3xy1LmWQvHPtoUAQzOfuhIIP/IeuH761viqU="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-2C8709"
    password: "4IYsoV6qPx0E"

captive_portal:

# Enable logging
logger:
  level: INFO
  baud_rate: 0
  logs:
    component: ERROR


  
uart:
  id: uart_bus
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  
switch:
  - platform: safe_mode
    name: "ESPKyoGate (Safe Mode)"

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_mancanza_rete,
        kyo32->sabotaggio_zona, 
        kyo32->sabotaggio_sistema,
        kyo32->warn_scomparsa_bpi,
        kyo32->warn_fusibile,
        kyo32->warn_batteria_bassa,
        kyo32->warn_guasto_linea_telefonica,
        kyo32->warn_codici_default,
        kyo32->warn_wireless,
        kyo32->sabotaggio_bpi,
        kyo32->sabotaggio_jam,
        kyo32->sabotaggio_wireless,
        kyo32->sabotaggio_chiave_falsa,

        &kyo32->zona[0],
        &kyo32->zona[1],
        &kyo32->zona[2],
        &kyo32->zona[3],

        &kyo32->zona_sabotaggio[0],
        &kyo32->zona_sabotaggio[1],
        &kyo32->zona_sabotaggio[2],
        &kyo32->zona_sabotaggio[3],

        &kyo32->zona_esclusa[0],
        &kyo32->zona_esclusa[1],
        &kyo32->zona_esclusa[2],
        &kyo32->zona_esclusa[3],

        &kyo32->memoria_allarme_zona[0],
        &kyo32->memoria_allarme_zona[1],
        &kyo32->memoria_allarme_zona[2],
        &kyo32->memoria_allarme_zona[3],

        &kyo32->memoria_sabotaggio_zona[0],
        &kyo32->memoria_sabotaggio_zona[1],
        &kyo32->memoria_sabotaggio_zona[2],
        &kyo32->memoria_sabotaggio_zona[3],

        &kyo32->allarme_area[0],
        &kyo32->allarme_area[1],
        &kyo32->allarme_area[2],
        &kyo32->allarme_area[3],

        &kyo32->inserimento_totale_area[0],
        &kyo32->inserimento_totale_area[1],
        &kyo32->inserimento_totale_area[2],
        &kyo32->inserimento_totale_area[3],

        &kyo32->inserimento_parziale_area[0],
        &kyo32->inserimento_parziale_area[1],
        &kyo32->inserimento_parziale_area[2],
        &kyo32->inserimento_parziale_area[3],

        &kyo32->inserimento_parziale_ritardo_0_area[0],
        &kyo32->inserimento_parziale_ritardo_0_area[1],
        &kyo32->inserimento_parziale_ritardo_0_area[2],
        &kyo32->inserimento_parziale_ritardo_0_area[3],

        &kyo32->disinserita_area[0],
        &kyo32->disinserita_area[1],
        &kyo32->disinserita_area[2],
        &kyo32->disinserita_area[3],

        &kyo32->stato_uscita[0],
        &kyo32->stato_uscita[1],
        &kyo32->stato_uscita[2],
        &kyo32->stato_uscita[3]
      };
    binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
      - id: warn_mancanza_rete
        name: "Mancanza Rete"
      - id: sabotaggio_zona
        name: "Sabotaggio Zona"
      - id: sabotaggio_sistema
        name: "Sabotaggio Sistema"
      - id: warn_scomparsa_bpi
        name: "Scomparsa BPI"
      - id: warn_fusibile
        name: "Fusibile"
      - id: warn_batteria_bassa
        name: "Batteria Bassa"
      - id: warn_guasto_linea_telefonica
        name: "Guasto Linea Telefonica"
      - id: warn_codici_default
        name: "Codici Default"
      - id: warn_wireless
        name: "Wireless"
      - id: sabotaggio_bpi
        name: "Sabotaggio BPI"
      - id: sabotaggio_jam
        name: "Sabotaggio Jam"
      - id: sabotaggio_wireless
        name: "Sabotaggio wireless"
      - id: sabotaggio_chiave_falsa
        name: "Sabotaggio Chiave Falsa"

      - id: zone_1
        name: "Porta Ingresso"
        device_class: "door"
      - id: zone_2
        name: "PFinestra Cucina"
        device_class: "window"
      - id: zone_3
        name: "PFinestra Sala"
        device_class: "window"
      - id: zone_4
        name: "Finestra Sala"
        device_class: "window"
      - id: zone_5
        name: "PIR Soggiorno"
        device_class: "motion"

      - id: zone_1_tampering
        name: "Sabot. Porta Ingresso"
      - id: zone_2_tampering
        name: "Sabot. PFinestra Cucina"
      - id: zone_3_tampering
        name: "Sabot. PFinestra Sala"
      - id: zone_4_tampering
        name: "Sabot. Finestra Sala"
      - id: zone_5_tampering
        name: "Sabot. PIR Soggiorno"

      #- id: excluded_zone_1
      #  name: "Escl. Sensore DT Taverna"
      #- id: excluded_zone_2
      #  name: "Escl. Finestra Taverna"
      #- id: excluded_zone_3
      #  name: "Escl. Sensore DT Garage"
      #- id: excluded_zone_4
      #  name: "Escl. Scuretto Finestra Lavanderia"

      - id: alarm_memory_zone_1
        name: "Mem. Allarme Porta Ingresso"
      - id: alarm_memory_zone_2
        name: "Mem. Allarme PFinestra Cucina"
      - id: alarm_memory_zone_3
        name: "Mem. Allarme PFinestra Sala"
      - id: alarm_memory_zone_4
        name: "Mem. Allarme Finestra Sala"
      - id: alarm_memory_zone_5
        name: "Mem. Allarme PIR Soggiorno"  

      - id: sabotage_memory_zone_1
        name: "Mem. Sabotaggio Porta Ingresso"
      - id: sabotage_memory_zone_2
        name: "Mem. Sabotaggio PFinestra Cucina"
      - id: sabotage_memory_zone_3
        name: "Mem. Sabotaggio PFinestra Sala"
      - id: sabotage_memory_zone_4
        name: "Mem. Sabotaggio Finestra Sala"
      - id: sabotage_memory_zone_5
        name: "Mem. Sabotaggio PIR Soggiorno"

      - id: alarm_area_1
        name: "Allarme Area 1"
      #- id: alarm_area_2
      #  name: "Allarme Area 2"
      #- id: alarm_area_3
      #  name: "Allarme Area 3"
      #- id: alarm_area_4
      #  name: "Allarme Area Sensori Interni"

      - id: enabled_total_area_1
        name: "Ins. Totale Casa"
      #- id: enabled_total_area_2
      #  name: "Ins. Totale Porte"
      #- id: enabled_total_area_3
      #  name: "Ins. Totale Sensori Giardino"
      #- id: enabled_total_area_4
      #  name: "Ins. Totale Sensori Interni"

      - id: enabled_partial_area_1
        name: "Ins. Parziale Casa"
      #- id: enabled_partial_area_2
      #  name: "Ins. Parziale Porte"
      #- id: enabled_partial_area_3
      #  name: "Ins. Parziale Sensori Giardino"
      #- id: enabled_partial_area_4
      #  name: "Ins. Parziale Sensori Interni"        

      - id: enabled_partial_delay_0_area_1
        name: "Ins. Parziale Ritardo 0 Casa"
      #- id: enabled_partial_delay_0_area_2
      #  name: "Ins. Parziale Ritardo 0 Porte"
      #- id: enabled_partial_delay_0_area_3
      #  name: "Ins. Parziale Ritardo 0 Sensori Giardino"
      #- id: enabled_partial_delay_0_area_4
      #  name: "Ins. Parziale Ritardo 0 Sensori Interni"

      - id: disabled_area_1
        name: "Allarme Totale"
      - id: disabled_area_2
        name: "Allarme Parziale"
      #- id: disabled_area_3
      #  name: "Disins. Sensori Giardino"
      #- id: disabled_area_4
      #  name: "Disins. Sensori Interni"
      
      - id: exit_status_1
        name: "Stato Uscita 1"

**Comment by pow3r77** [comment]
`esphome:
  name: espkyogatebox
  friendly_name: Allarme Casa
  comment: Alarm System Serial to HA controller
  includes:
    - bentel-kyo/bentel_kyo32.h

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: "uJxOXuy3xy1LmWQvHPtoUAQzOfuhIIP/IeuH761viqU="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-2C8709"
    password: "4IYsoV6qPx0E"

captive_portal:

# Enable logging
logger:
  level: INFO
  baud_rate: 0
  logs:
    component: ERROR


  
uart:
  id: uart_bus
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  
switch:
  - platform: safe_mode
    name: "ESPKyoGate (Safe Mode)"

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_mancanza_rete,
        kyo32->sabotaggio_zona, 
        kyo32->sabotaggio_sistema,
        kyo32->warn_scomparsa_bpi,
        kyo32->warn_fusibile,
        kyo32->warn_batteria_bassa,
        kyo32->warn_guasto_linea_telefonica,
        kyo32->warn_codici_default,
        kyo32->warn_wireless,
        kyo32->sabotaggio_bpi,
        kyo32->sabotaggio_jam,
        kyo32->sabotaggio_wireless,
        kyo32->sabotaggio_chiave_falsa,

        &kyo32->zona[0],
        &kyo32->zona[1],
        &kyo32->zona[2],
        &kyo32->zona[3],

        &kyo32->zona_sabotaggio[0],
        &kyo32->zona_sabotaggio[1],
        &kyo32->zona_sabotaggio[2],
        &kyo32->zona_sabotaggio[3],

        &kyo32->zona_esclusa[0],
        &kyo32->zona_esclusa[1],
        &kyo32->zona_esclusa[2],
        &kyo32->zona_esclusa[3],

        &kyo32->memoria_allarme_zona[0],
        &kyo32->memoria_allarme_zona[1],
        &kyo32->memoria_allarme_zona[2],
        &kyo32->memoria_allarme_zona[3],

        &kyo32->memoria_sabotaggio_zona[0],
        &kyo32->memoria_sabotaggio_zona[1],
        &kyo32->memoria_sabotaggio_zona[2],
        &kyo32->memoria_sabotaggio_zona[3],

        &kyo32->allarme_area[0],
        &kyo32->allarme_area[1],
        &kyo32->allarme_area[2],
        &kyo32->allarme_area[3],

        &kyo32->inserimento_totale_area[0],
        &kyo32->inserimento_totale_area[1],
        &kyo32->inserimento_totale_area[2],
        &kyo32->inserimento_totale_area[3],

        &kyo32->inserimento_parziale_area[0],
        &kyo32->inserimento_parziale_area[1],
        &kyo32->inserimento_parziale_area[2],
        &kyo32->inserimento_parziale_area[3],

        &kyo32->inserimento_parziale_ritardo_0_area[0],
        &kyo32->inserimento_parziale_ritardo_0_area[1],
        &kyo32->inserimento_parziale_ritardo_0_area[2],
        &kyo32->inserimento_parziale_ritardo_0_area[3],

        &kyo32->disinserita_area[0],
        &kyo32->disinserita_area[1],
        &kyo32->disinserita_area[2],
        &kyo32->disinserita_area[3],

        &kyo32->stato_uscita[0],
        &kyo32->stato_uscita[1],
        &kyo32->stato_uscita[2],
        &kyo32->stato_uscita[3]
      };
    binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
      - id: warn_mancanza_rete
        name: "Mancanza Rete"
      - id: sabotaggio_zona
        name: "Sabotaggio Zona"
      - id: sabotaggio_sistema
        name: "Sabotaggio Sistema"
      - id: warn_scomparsa_bpi
        name: "Scomparsa BPI"
      - id: warn_fusibile
        name: "Fusibile"
      - id: warn_batteria_bassa
        name: "Batteria Bassa"
      - id: warn_guasto_linea_telefonica
        name: "Guasto Linea Telefonica"
      - id: warn_codici_default
        name: "Codici Default"
      - id: warn_wireless
        name: "Wireless"
      - id: sabotaggio_bpi
        name: "Sabotaggio BPI"
      - id: sabotaggio_jam
        name: "Sabotaggio Jam"
      - id: sabotaggio_wireless
        name: "Sabotaggio wireless"
      - id: sabotaggio_chiave_falsa
        name: "Sabotaggio Chiave Falsa"

      - id: zone_1
        name: "Porta Ingresso"
        device_class: "door"
      - id: zone_2
        name: "PFinestra Cucina"
        device_class: "window"
      - id: zone_3
        name: "PFinestra Sala"
        device_class: "window"
      - id: zone_4
        name: "Finestra Sala"
        device_class: "window"
      - id: zone_5
        name: "PIR Soggiorno"
        device_class: "motion"

      - id: zone_1_tampering
        name: "Sabot. Porta Ingresso"
      - id: zone_2_tampering
        name: "Sabot. PFinestra Cucina"
      - id: zone_3_tampering
        name: "Sabot. PFinestra Sala"
      - id: zone_4_tampering
        name: "Sabot. Finestra Sala"
      - id: zone_5_tampering
        name: "Sabot. PIR Soggiorno"

      #- id: excluded_zone_1
      #  name: "Escl. Sensore DT Taverna"
      #- id: excluded_zone_2
      #  name: "Escl. Finestra Taverna"
      #- id: excluded_zone_3
      #  name: "Escl. Sensore DT Garage"
      #- id: excluded_zone_4
      #  name: "Escl. Scuretto Finestra Lavanderia"

      - id: alarm_memory_zone_1
        name: "Mem. Allarme Porta Ingresso"
      - id: alarm_memory_zone_2
        name: "Mem. Allarme PFinestra Cucina"
      - id: alarm_memory_zone_3
        name: "Mem. Allarme PFinestra Sala"
      - id: alarm_memory_zone_4
        name: "Mem. Allarme Finestra Sala"
      - id: alarm_memory_zone_5
        name: "Mem. Allarme PIR Soggiorno"  

      - id: sabotage_memory_zone_1
        name: "Mem. Sabotaggio Porta Ingresso"
      - id: sabotage_memory_zone_2
        name: "Mem. Sabotaggio PFinestra Cucina"
      - id: sabotage_memory_zone_3
        name: "Mem. Sabotaggio PFinestra Sala"
      - id: sabotage_memory_zone_4
        name: "Mem. Sabotaggio Finestra Sala"
      - id: sabotage_memory_zone_5
        name: "Mem. Sabotaggio PIR Soggiorno"

      - id: alarm_area_1
        name: "Allarme Area 1"
      #- id: alarm_area_2
      #  name: "Allarme Area 2"
      #- id: alarm_area_3
      #  name: "Allarme Area 3"
      #- id: alarm_area_4
      #  name: "Allarme Area Sensori Interni"

      - id: enabled_total_area_1
        name: "Ins. Totale Casa"
      #- id: enabled_total_area_2
      #  name: "Ins. Totale Porte"
      #- id: enabled_total_area_3
      #  name: "Ins. Totale Sensori Giardino"
      #- id: enabled_total_area_4
      #  name: "Ins. Totale Sensori Interni"

      - id: enabled_partial_area_1
        name: "Ins. Parziale Casa"
      #- id: enabled_partial_area_2
      #  name: "Ins. Parziale Porte"
      #- id: enabled_partial_area_3
      #  name: "Ins. Parziale Sensori Giardino"
      #- id: enabled_partial_area_4
      #  name: "Ins. Parziale Sensori Interni"        

      - id: enabled_partial_delay_0_area_1
        name: "Ins. Parziale Ritardo 0 Casa"
      #- id: enabled_partial_delay_0_area_2
      #  name: "Ins. Parziale Ritardo 0 Porte"
      #- id: enabled_partial_delay_0_area_3
      #  name: "Ins. Parziale Ritardo 0 Sensori Giardino"
      #- id: enabled_partial_delay_0_area_4
      #  name: "Ins. Parziale Ritardo 0 Sensori Interni"

      - id: disabled_area_1
        name: "Allarme Totale"
      - id: disabled_area_2
        name: "Allarme Parziale"
      #- id: disabled_area_3
      #  name: "Disins. Sensori Giardino"
      #- id: disabled_area_4
      #  name: "Disins. Sensori Interni"
      
      - id: exit_status_1
        name: "Stato Uscita 1"    `

**Comment by pow3r77** [comment]
```
esphome:
  name: espkyogatebox
  friendly_name: Allarme Casa
  comment: Alarm System Serial to HA controller
  includes:
    - bentel-kyo/bentel_kyo32.h

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: "uJxOXuy3xy1LmWQvHPtoUAQzOfuhIIP/IeuH761viqU="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-2C8709"
    password: "4IYsoV6qPx0E"

captive_portal:

# Enable logging
logger:
  level: INFO
  baud_rate: 0
  logs:
    component: ERROR


  
uart:
  id: uart_bus
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  
switch:
  - platform: safe_mode
    name: "ESPKyoGate (Safe Mode)"

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_mancanza_rete,
        kyo32->sabotaggio_zona, 
        kyo32->sabotaggio_sistema,
        kyo32->warn_scomparsa_bpi,
        kyo32->warn_fusibile,
        kyo32->warn_batteria_bassa,
        kyo32->warn_guasto_linea_telefonica,
        kyo32->warn_codici_default,
        kyo32->warn_wireless,
        kyo32->sabotaggio_bpi,
        kyo32->sabotaggio_jam,
        kyo32->sabotaggio_wireless,
        kyo32->sabotaggio_chiave_falsa,

        &kyo32->zona[0],
        &kyo32->zona[1],
        &kyo32->zona[2],
        &kyo32->zona[3],

        &kyo32->zona_sabotaggio[0],
        &kyo32->zona_sabotaggio[1],
        &kyo32->zona_sabotaggio[2],
        &kyo32->zona_sabotaggio[3],

        &kyo32->zona_esclusa[0],
        &kyo32->zona_esclusa[1],
        &kyo32->zona_esclusa[2],
        &kyo32->zona_esclusa[3],

        &kyo32->memoria_allarme_zona[0],
        &kyo32->memoria_allarme_zona[1],
        &kyo32->memoria_allarme_zona[2],
        &kyo32->memoria_allarme_zona[3],

        &kyo32->memoria_sabotaggio_zona[0],
        &kyo32->memoria_sabotaggio_zona[1],
        &kyo32->memoria_sabotaggio_zona[2],
        &kyo32->memoria_sabotaggio_zona[3],

        &kyo32->allarme_area[0],
        &kyo32->allarme_area[1],
        &kyo32->allarme_area[2],
        &kyo32->allarme_area[3],

        &kyo32->inserimento_totale_area[0],
        &kyo32->inserimento_totale_area[1],
        &kyo32->inserimento_totale_area[2],
        &kyo32->inserimento_totale_area[3],

        &kyo32->inserimento_parziale_area[0],
        &kyo32->inserimento_parziale_area[1],
        &kyo32->inserimento_parziale_area[2],
        &kyo32->inserimento_parziale_area[3],

        &kyo32->inserimento_parziale_ritardo_0_area[0],
        &kyo32->inserimento_parziale_ritardo_0_area[1],
        &kyo32->inserimento_parziale_ritardo_0_area[2],
        &kyo32->inserimento_parziale_ritardo_0_area[3],

        &kyo32->disinserita_area[0],
        &kyo32->disinserita_area[1],
        &kyo32->disinserita_area[2],
        &kyo32->disinserita_area[3],

        &kyo32->stato_uscita[0],
        &kyo32->stato_uscita[1],
        &kyo32->stato_uscita[2],
        &kyo32->stato_uscita[3]
      };
    binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
      - id: warn_mancanza_rete
        name: "Mancanza Rete"
      - id: sabotaggio_zona
        name: "Sabotaggio Zona"
      - id: sabotaggio_sistema
        name: "Sabotaggio Sistema"
      - id: warn_scomparsa_bpi
        name: "Scomparsa BPI"
      - id: warn_fusibile
        name: "Fusibile"
      - id: warn_batteria_bassa
        name: "Batteria Bassa"
      - id: warn_guasto_linea_telefonica
        name: "Guasto Linea Telefonica"
      - id: warn_codici_default
        name: "Codici Default"
      - id: warn_wireless
        name: "Wireless"
      - id: sabotaggio_bpi
        name: "Sabotaggio BPI"
      - id: sabotaggio_jam
        name: "Sabotaggio Jam"
      - id: sabotaggio_wireless
        name: "Sabotaggio wireless"
      - id: sabotaggio_chiave_falsa
        name: "Sabotaggio Chiave Falsa"

      - id: zone_1
        name: "Porta Ingresso"
        device_class: "door"
      - id: zone_2
        name: "PFinestra Cucina"
        device_class: "window"
      - id: zone_3
        name: "PFinestra Sala"
        device_class: "window"
      - id: zone_4
        name: "Finestra Sala"
        device_class: "window"
      - id: zone_5
        name: "PIR Soggiorno"
        device_class: "motion"

      - id: zone_1_tampering
        name: "Sabot. Porta Ingresso"
      - id: zone_2_tampering
        name: "Sabot. PFinestra Cucina"
      - id: zone_3_tampering
        name: "Sabot. PFinestra Sala"
      - id: zone_4_tampering
        name: "Sabot. Finestra Sala"
      - id: zone_5_tampering
        name: "Sabot. PIR Soggiorno"

      #- id: excluded_zone_1
      #  name: "Escl. Sensore DT Taverna"
      #- id: excluded_zone_2
      #  name: "Escl. Finestra Taverna"
      #- id: excluded_zone_3
      #  name: "Escl. Sensore DT Garage"
      #- id: excluded_zone_4
      #  name: "Escl. Scuretto Finestra Lavanderia"

      - id: alarm_memory_zone_1
        name: "Mem. Allarme Porta Ingresso"
      - id: alarm_memory_zone_2
        name: "Mem. Allarme PFinestra Cucina"
      - id: alarm_memory_zone_3
        name: "Mem. Allarme PFinestra Sala"
      - id: alarm_memory_zone_4
        name: "Mem. Allarme Finestra Sala"
      - id: alarm_memory_zone_5
        name: "Mem. Allarme PIR Soggiorno"  

      - id: sabotage_memory_zone_1
        name: "Mem. Sabotaggio Porta Ingresso"
      - id: sabotage_memory_zone_2
        name: "Mem. Sabotaggio PFinestra Cucina"
      - id: sabotage_memory_zone_3
        name: "Mem. Sabotaggio PFinestra Sala"
      - id: sabotage_memory_zone_4
        name: "Mem. Sabotaggio Finestra Sala"
      - id: sabotage_memory_zone_5
        name: "Mem. Sabotaggio PIR Soggiorno"

      - id: alarm_area_1
        name: "Allarme Area 1"
      #- id: alarm_area_2
      #  name: "Allarme Area 2"
      #- id: alarm_area_3
      #  name: "Allarme Area 3"
      #- id: alarm_area_4
      #  name: "Allarme Area Sensori Interni"

      - id: enabled_total_area_1
        name: "Ins. Totale Casa"
      #- id: enabled_total_area_2
      #  name: "Ins. Totale Porte"
      #- id: enabled_total_area_3
      #  name: "Ins. Totale Sensori Giardino"
      #- id: enabled_total_area_4
      #  name: "Ins. Totale Sensori Interni"

      - id: enabled_partial_area_1
        name: "Ins. Parziale Casa"
      #- id: enabled_partial_area_2
      #  name: "Ins. Parziale Porte"
      #- id: enabled_partial_area_3
      #  name: "Ins. Parziale Sensori Giardino"
      #- id: enabled_partial_area_4
      #  name: "Ins. Parziale Sensori Interni"        

      - id: enabled_partial_delay_0_area_1
        name: "Ins. Parziale Ritardo 0 Casa"
      #- id: enabled_partial_delay_0_area_2
      #  name: "Ins. Parziale Ritardo 0 Porte"
      #- id: enabled_partial_delay_0_area_3
      #  name: "Ins. Parziale Ritardo 0 Sensori Giardino"
      #- id: enabled_partial_delay_0_area_4
      #  name: "Ins. Parziale Ritardo 0 Sensori Interni"

      - id: disabled_area_1
        name: "Allarme Totale"
      - id: disabled_area_2
        name: "Allarme Parziale"
      #- id: disabled_area_3
      #  name: "Disins. Sensori Giardino"
      #- id: disabled_area_4
      #  name: "Disins. Sensori Interni"
      
      - id: exit_status_1
        name: "Stato Uscita 1"    
```

**Comment by lorenzo-deluca** [comment]
Ciao, allora, confermo che c'è sicuramente un problema di configurazione.
Fai attenzione, le variabili mappate nel return DEVONO essere mappate uno a uno (in esatto ordine) con le variabili sotto.

Nella tua configurazione già vedo che le zone ritornate sono 4 (da 0 a 3), mentre quelle mappate sono 5, idem per le zone di sabotaggio (allego screen).
Sfortunatamente, essendo tutti binary sensors, se il numero è uguale funziona lo stesso ma ovviamente ti va a mappare logicamente valori diversi rispetto a quanto ti aspetti.

![image](https://github.com/lorenzo-deluca/espkyogate/assets/32000123/2f110337-21eb-4ca4-be63-e7b000701f0e)

In futuro vedrò se riesco a trovare un mapping più semplice perché non sei il primo che cade in questo errore 👍 

Fammi sapere come va ;)

**Comment by pow3r77** [comment]
Perfetto! Grazie mille per le spiegazioni! Adesso ho sistemato tutto e mi tornano tutti i comandi.
Riguardo alla possibilità di inserire il comando per interrompere le chiamate? Ritieni si possa riuscire?

**Comment by lorenzo-deluca** [comment]
Ottimo, mi sembrava strano che solo tu avessi problemi.
Per il comando di reset chiamate il reset allarme non basta vero?
Il fatto è che non avendo il compositore mi dovete dire voi come funziona 😅 fondamentalmente, dal software Bentel dell'installatore si può fare quel comando? Se si come?

**Comment by pow3r77** [comment]
Dal software bentel non mi pare di aver, lo puoi fare come comando dalla centrale.

https://www.youtube.com/watch?v=proCnc0EoHE
