### ISSUE TITLE
Lorenzo buongiorno,

### ISSUE THREAD

**Issue by pow3r77** [lorenzo-deluca/espkyogate#51]
Lorenzo buongiorno, 
approfitto nuovamente della tua cortesia, le uscite me le dà tutte in stato "Sconocsciuto"
Vedi qualche errore che mi sfugge nel codice?

`
binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_mancanza_rete,
        kyo32->sabotaggio_zona, 
        kyo32->sabotaggio_sistema,
        kyo32->warn_scomparsa_bpi,
        kyo32->warn_fusibile,
        kyo32->warn_batteria_bassa,
        kyo32->warn_guasto_linea_telefonica,
        kyo32->warn_codici_default,
        kyo32->warn_wireless,
        kyo32->sabotaggio_bpi,
        kyo32->sabotaggio_jam,
        kyo32->sabotaggio_wireless,
        kyo32->sabotaggio_chiave_falsa,

        &kyo32->zona[0],
        &kyo32->zona[1],
        &kyo32->zona[2],
        &kyo32->zona[3],
        &kyo32->zona[4],

        &kyo32->zona_sabotaggio[0],
        &kyo32->zona_sabotaggio[1],
        &kyo32->zona_sabotaggio[2],
        &kyo32->zona_sabotaggio[3],
        &kyo32->zona_sabotaggio[4],

        &kyo32->zona_esclusa[0],
        &kyo32->zona_esclusa[1],
        &kyo32->zona_esclusa[2],
        &kyo32->zona_esclusa[3],
        &kyo32->zona_esclusa[4],

        &kyo32->memoria_allarme_zona[0],
        &kyo32->memoria_allarme_zona[1],
        &kyo32->memoria_allarme_zona[2],
        &kyo32->memoria_allarme_zona[3],
        &kyo32->memoria_allarme_zona[4],

        &kyo32->memoria_sabotaggio_zona[0],
        &kyo32->memoria_sabotaggio_zona[1],
        &kyo32->memoria_sabotaggio_zona[2],
        &kyo32->memoria_sabotaggio_zona[3],
        &kyo32->memoria_sabotaggio_zona[4],

        &kyo32->allarme_area[0],
        &kyo32->allarme_area[1],
        &kyo32->allarme_area[2],
        &kyo32->allarme_area[3],

        &kyo32->inserimento_totale_area[0],
        &kyo32->inserimento_totale_area[1],
        &kyo32->inserimento_totale_area[2],
        &kyo32->inserimento_totale_area[3],

        &kyo32->inserimento_parziale_area[0],
        &kyo32->inserimento_parziale_area[1],
        &kyo32->inserimento_parziale_area[2],
        &kyo32->inserimento_parziale_area[3],

        &kyo32->inserimento_parziale_ritardo_0_area[0],
        &kyo32->inserimento_parziale_ritardo_0_area[1],
        &kyo32->inserimento_parziale_ritardo_0_area[2],
        &kyo32->inserimento_parziale_ritardo_0_area[3],

        &kyo32->disinserita_area[0],
        &kyo32->disinserita_area[1],
        &kyo32->disinserita_area[2],
        &kyo32->disinserita_area[3],

        &kyo32->stato_uscita[0],
        &kyo32->stato_uscita[1],
        &kyo32->stato_uscita[2],
        &kyo32->stato_uscita[3],
        };
    binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
      - id: warn_mancanza_rete
        name: "Mancanza Rete"
      - id: sabotaggio_zona
        name: "Sabotaggio Zona"
      - id: sabotaggio_sistema
        name: "Sabotaggio Sistema"
      - id: warn_scomparsa_bpi
        name: "Scomparsa BPI"
      - id: warn_fusibile
        name: "Fusibile"
      - id: warn_batteria_bassa
        name: "Batteria Bassa"
      - id: warn_guasto_linea_telefonica
        name: "Guasto Linea Telefonica"
      - id: warn_codici_default
        name: "Codici Default"
      - id: warn_wireless
        name: "Wireless"
      - id: sabotaggio_bpi
        name: "Sabotaggio BPI"
      - id: sabotaggio_jam
        name: "Sabotaggio Jam"
      - id: sabotaggio_wireless
        name: "Sabotaggio wireless"
      - id: sabotaggio_chiave_falsa
        name: "Sabotaggio Chiave Falsa"

      - id: zone_1
        name: "PIR Cortile"
        device_class: "door"
      - id: zone_2
        name: "PIR Cantine"
        device_class: "window"
      - id: zone_3
        name: "Porta Garage"
        device_class: "window"
      - id: zone_4
        name: "Zona 4"
        device_class: "window"
      - id: zone_5
        name: "Zona 5"
        device_class: "motion"

      - id: zone_1_tampering
        name: "Sabot. PIR Cortile"
      - id: zone_2_tampering
        name: "Sabot. PIR Cantine"
      - id: zone_3_tampering
        name: "Sabot. Porta Garage"
      - id: zone_4_tampering
        name: "Sabot. Zona 4"
      - id: zone_5_tampering
        name: "Sabot. Zona 5"

      - id: excluded_zone_1
        name: "Escl. PIR Cortile"
      - id: excluded_zone_2
        name: "Escl. PIR Cantine"
      - id: excluded_zone_3
        name: "Escl. Porta Garage"
      - id: excluded_zone_4
        name: "Escl. Zona 4"
      - id: excluded_zone_5
        name: "Escl. Zona 5"  

      - id: alarm_memory_zone_1
        name: "Mem. Allarme PIR Cortile"
      - id: alarm_memory_zone_2
        name: "Mem. Allarme PIR Cantine"
      - id: alarm_memory_zone_3
        name: "Mem. Allarme Porta Garage"
      - id: alarm_memory_zone_4
        name: "Mem. Allarme Zona 4"
      - id: alarm_memory_zone_5
        name: "Mem. Allarme Zona 5"  

      - id: sabotage_memory_zone_1
        name: "Mem. Sabotaggio PIR Cortile"
      - id: sabotage_memory_zone_2
        name: "Mem. Sabotaggio PIR Cantine"
      - id: sabotage_memory_zone_3
        name: "Mem. Sabotaggio Porta Garage"
      - id: sabotage_memory_zone_4
        name: "Mem. Sabotaggio Zona 4"
      - id: sabotage_memory_zone_5
        name: "Mem. Sabotaggio Zona 5"

      - id: alarm_area_1
        name: "Allarme Area 1"
      - id: alarm_area_2
        name: "Allarme Area 2"
      - id: alarm_area_3
        name: "Allarme Area 3"
      - id: alarm_area_4
        name: "Allarme Area 4"

      - id: enabled_total_area_1
        name: "Ins. Totale"
      - id: enabled_total_area_2
        name: "Ins. Totale Area 2"
      - id: enabled_total_area_3
        name: "Ins. Totale Area 3"
      - id: enabled_total_area_4
        name: "Ins. Totale Area 4"

      - id: enabled_partial_area_1
        name: "Ins. Parziale Area 1"
      - id: enabled_partial_area_2
        name: "Ins. Parziale Area 2"
      - id: enabled_partial_area_3
        name: "Ins. Parziale Area 3"
      - id: enabled_partial_area_4
        name: "Ins. Parziale Area 4"        

      - id: enabled_partial_delay_0_area_1
        name: "Ins. Parziale Ritardo 0 Totale"
      - id: enabled_partial_delay_0_area_2
        name: "Ins. Parziale Ritardo 0 Parziale"
      - id: enabled_partial_delay_0_area_3
        name: "Ins. Parziale Ritardo 0 Area 3"
      - id: enabled_partial_delay_0_area_4
        name: "Ins. Parziale Ritardo 0 Area 4"

      - id: disabled_area_1
        name: "Disins. Allarme Totale"
      - id: disabled_area_2
        name: "Disins. Allarme Parziale"
      - id: disabled_area_3
        name: "Disins. Area 3"
      - id: disabled_area_4
        name: "Disins. Area 4"
      
      - id: exit_status_1
        name: "Stato Uscita Allarme Totoale"
      - id: exit_status_2
        name: "Stato Uscita Allarme Totoale"
      - id: exit_status_3
        name: "Stato Uscita Allarme Attivo" 
`

**Comment by lorenzo-deluca** [comment]
Buonasera, premesso che non mi posso mettere a controllare le configurazioni complete di tutti gli utenti :)

Se non ho visto male nella return lambda ritorni 4 uscite stato_uscita[0] - [3] mentre nei sensori ne hai definite 3.

Potrebbe essere questo? Fammi sapere eventualmente.

Ciao ;)
