### ISSUE TITLE
Sabotaggio sistema

### ISSUE THREAD

**Issue by serucci** [lorenzo-deluca/espkyogate#52]
Buongiorno, l'attivazione dell'allarme Sabotaggio Sistema , l'apertura o il corto della linea AS 24h per intenderci,manda in blocco il mosulo ESP che smette di comunicare con la centrale. Questo ,secondo me ,è un grosso problema
Il binary sensor Comunicazione Centrale correttamente si spegne . Per il ripristino non ho trovato altro modo se non lo spegnimento e riaccensione dello stesso.

**Comment by lorenzo-deluca** [comment]
Ciao, ho testato con la mia centrale Kyo32G e l'antisabotaggio sistema viene correttamente segnalato con il binary_sensor.sabotaggio_sistema senza bloccare il modulo ESP.
