### ISSUE TITLE
Pulsanti attivazione

### ISSUE THREAD

**Issue by marcozovo** [lorenzo-deluca/espkyogate#54]
Innanzitutto grazie per il progetto, oggi sono riuscito a portare a termine una parte e ti faccio i complimenti.
Ti vorrei segnalare una piccola imprecisione: viene indicato come "service: esphome.espkyogate_arm_area" ma quello corretto è "**service: esphome.espkyogatebox_arm_area**"

**Comment by lorenzo-deluca** [comment]
Ciao, si, è un errore di typo.. il nome dipende dal nome del progetto che dai su esphome.
Effettivamente l'avevo cambiato perché il file di esempio riportava espkyogatebox, ora ho sistemato ;)

Comunque funziona tutto?
