### ISSUE TITLE
stato binary sensor allarmi

### ISSUE THREAD

**Issue by serucci** [lorenzo-deluca/espkyogate#57]
Come già scritto nella issue chiusa ,non cambiano di stato...ciao

**Comment by serucci** [comment]
con molto piacere caffe...offerti

**Comment by newtoni85** [comment]
Buongiorno, non sono esperto di esphome.... nella mia configurazione i sensori allarme area funzionano.
<img width="695" alt="Schermata 2024-04-20 alle 11 25 57" src="https://github.com/lorenzo-deluca/espkyogate/assets/123250397/94b6266e-5cfa-4e43-b834-194fb316babe">

**Comment by lorenzo-deluca** [comment]
> Buongiorno, non sono esperto di esphome.... nella mia configurazione i sensori allarme area funzionano. <img alt="Schermata 2024-04-20 alle 11 25 57" width="695" src="https://private-user-images.githubusercontent.com/123250397/324168356-94b6266e-5cfa-4e43-b834-194fb316babe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDU5OTksIm5iZiI6MTcxMzYwNTY5OSwicGF0aCI6Ii8xMjMyNTAzOTcvMzI0MTY4MzU2LTk0YjYyNjZlLTVjZmEtNGU0My1iODM0LTE5NGZiMzE2YmFiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwOTM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2I3YTU0M2FjODM1OTZlODVkMTZiNzk1ZTk0NWU0YzU5ZTQ5YTZhY2I1OTRhNTMzNjI2NjJkNTQ0YjM5ZjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MbVkf7U3F33RI5Y9g-cyhaS9y-4hhsRVyZY0MdvnM3M">

Infatti anche io ricordavo funzionassero.. stai usando l'ultima versione? la centrale è una Kyo8 o Kyo32? Puoi postare la tua configurazione yaml (senza password, ovviamente)..

Grazie!

**Comment by newtoni85** [comment]
> > Buongiorno, non sono esperto di esphome.... nella mia configurazione i sensori allarme area funzionano. <img alt="Schermata 2024-04-20 alle 11 25 57" width="695" src="https://private-user-images.githubusercontent.com/123250397/324168356-94b6266e-5cfa-4e43-b834-194fb316babe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDU5OTksIm5iZiI6MTcxMzYwNTY5OSwicGF0aCI6Ii8xMjMyNTAzOTcvMzI0MTY4MzU2LTk0YjYyNjZlLTVjZmEtNGU0My1iODM0LTE5NGZiMzE2YmFiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwOTM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2I3YTU0M2FjODM1OTZlODVkMTZiNzk1ZTk0NWU0YzU5ZTQ5YTZhY2I1OTRhNTMzNjI2NjJkNTQ0YjM5ZjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MbVkf7U3F33RI5Y9g-cyhaS9y-4hhsRVyZY0MdvnM3M">
> 
> Infatti anche io ricordavo funzionassero.. stai usando l'ultima versione? la centrale è una Kyo8 o Kyo32? Puoi postare la tua configurazione yaml (senza password, ovviamente)..
> 
> Grazie!

la centrale è una Kyo32G e attulamente il file bentel_kyo32.h utilizzato è la precedente versione a quella che hai pubblicato tre giorni fa. per la configurazione nessun problema come funziona posso inserita nei commenti?

**Comment by newtoni85** [comment]
esphome:
  name: bentel
  friendly_name: bentel
  includes:
    - build/bentel/bentel_kyo32.h

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino


# Enable logging
logger:
  level: info
  baud_rate: 0

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: EVEN


# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  password: 

wifi:
  ssid: 
  password:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 
    password: 

captive_portal:
  
switch:

  - platform: safe_mode
    name: "ESPKyoGate (Safe Mode)"


binary_sensor:
- platform: custom
  lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_batteria_bassa,
        &kyo32->zona[0],
        &kyo32->zona[1],
        &kyo32->zona[2],
        &kyo32->zona[3],
        &kyo32->zona[4],
        &kyo32->zona[5],
        &kyo32->zona[6],
        &kyo32->zona[7],
        &kyo32->zona[8],
        &kyo32->zona[9],
        &kyo32->zona[10],
        &kyo32->zona[11],
        &kyo32->zona[12],
        &kyo32->zona[13],
        &kyo32->zona[14],
        &kyo32->zona[15],
        &kyo32->zona[16],
        &kyo32->zona[17],
        &kyo32->zona[18],
        &kyo32->zona[19],
        &kyo32->zona[20],
        &kyo32->zona[21],
        &kyo32->zona[22],
        &kyo32->zona[23],
        &kyo32->zona[24],
        &kyo32->zona[25],
        &kyo32->zona[26],
        &kyo32->zona[27],
        &kyo32->zona[28],
        &kyo32->zona[29],
        &kyo32->zona[30],
        &kyo32->zona[31],

        &kyo32->allarme_area[0],
        &kyo32->allarme_area[1],
        &kyo32->allarme_area[2],
        &kyo32->allarme_area[3],
        &kyo32->allarme_area[4],
        &kyo32->allarme_area[5],
        &kyo32->allarme_area[6],

        &kyo32->inserimento_totale_area[0],
        &kyo32->inserimento_totale_area[1],
        &kyo32->inserimento_totale_area[2],
        &kyo32->inserimento_totale_area[3],
        &kyo32->inserimento_totale_area[4],
        &kyo32->inserimento_totale_area[5],
        &kyo32->inserimento_totale_area[6],
        
        &kyo32->disinserita_area[0],
        &kyo32->disinserita_area[1],
        &kyo32->disinserita_area[2],
        &kyo32->disinserita_area[3],
        &kyo32->disinserita_area[4],
        &kyo32->disinserita_area[5],
        &kyo32->disinserita_area[6],
      
        
        };

  binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
      - id: warn_batteria_bassa
        name: "Batteria Bassa"
      - id: zona_1
        name: "Volumetrico Rustico"
        device_class: "motion"
      - id: zona_2
        name: "Volumetrico Sala"
        device_class: "motion"
      - id: zona_3
        name: "Volumetrico Camera"
        device_class: "motion"
      - id: zona_4
        name: "Portone Taverna"
        device_class: "door"
      - id: zona_5
        name: "Porta Cucina Rustico"
        device_class: "door"
      - id: zona_6
        name: "Porta Ingresso Rustico"
        device_class: "door"
      - id: zona_7
        name: "Porta Scanna fosso"
        device_class: "door"
      - id: zona_8
        name: "Finestra Camera Rustico"
        device_class: "window"
      - id: zona_9
        name: "Finestra Bagno Rustico"
        device_class: "window"
      - id: zona_10
        name: "Finestra Ingresso Piano Terra"
        device_class: "window"
      - id: zona_11
        name: "Porta Finestra PT sinistra Sala"
        device_class: "door"
      - id: zona_12
        name: "Persiana porta PT sinistra Sala"
        device_class: "door"
      - id: zona_13
        name: "Porta Finestra Sala destra"
        device_class: "door"
      - id: zona_14
        name: "Persiana porta PT destra Sala"
        device_class: "door"
      - id: zona_15
        name: "Finestra Cucina"
        device_class: "window"
      - id: zona_16
        name: "Persiana Cucina"
        device_class: "window"
      - id: zona_17
        name: "vuota"
        device_class: "window"
      - id: zona_18
        name: "vuota1"
        device_class: "window"
      - id: zona_19
        name: "Finestra bagno PT"
        device_class: "window"
      - id: zona_20
        name: "Ingresso"
        device_class: "door"
      - id: zona_21
        name: "Finestra Camera"
        device_class: "door"
      - id: zona_22
        name: "Persiana Camera"
        device_class: "door"
      - id: zona_23
        name: "Porta Finestra Camera"
        device_class: "door"
      - id: zona_24
        name: "Persina Porta Finestra Camera"
        device_class: "door"
      - id: zona_25
        name: "Finestra Bagno Camera"
        device_class: "window"
      - id: zona_26
        name: "Persiana Bagno camera"
        device_class: "window"
      - id: zona_27
        name: "Finestra Scale Camera"
        device_class: "window"
      - id: zona_28
        name: "Persiana Finestra Scale Camera"
        device_class: "window"
      - id: zona_29
        name: "Porta Finestra Camerina"
        device_class: "door"
      - id: zona_30
        name: "Persiana Porta Finestra Camerina"
        device_class: "door"
      - id: zona_31
        name: "Finestra “Caldaia"
        device_class: "window"

      - id: allarme_area_0 
        name: "Allarme Area 0"
      - id: allarme_area_1
        name: "Allarme Area 1"
      - id: allarme_area_2
        name: "Allarme Area 2"
      - id: allarme_area_3
        name: "Allarme Area 3"
      - id: allarme_area_4
        name: "Allarme Area 4"
      - id: allarme_area_5
        name: "Allarme Area 5"
      - id: allarme_area_6
        name: "Allarme Area 6"
    
      - id: inserimento_totale_area_0
        name: "Inserimento Totale Area 0"
      - id: inserimento_totale_area_1
        name: "Inserimento Totale Area 1"
      - id: inserimento_totale_area_2
        name: "Inserimento Totale Area 2"
      - id: inserimento_totale_area_3
        name: "Inserimento Totale Area 3"
      - id: inserimento_totale_area_4
        name: "Inserimento Totale Area 4"
      - id: inserimento_totale_area_5
        name: "Inserimento Totale Area 5"
      - id: inserimento_totale_area_6
        name: "Inserimento Totale Area 6"

      - id: disinserita_area_0
        name: "Disinserita Area 0"
      - id: disinserita_area_1
        name: "Disinserita Area 1"
      - id: disinserita_area_2
        name: "Disinserita Area 2"
      - id: disinserita_area_3
        name: "Disinserita Area 3"
      - id: disinserita_area_4
        name: "Disinserita Area 4"
      - id: disinserita_area_5
        name: "Disinserita Area 5"
      - id: disinserita_area_6
        name: "Disinserita Area 6"

**Comment by lorenzo-deluca** [comment]
Grazie @newtoni85 , (ho editato il commento per la formattazione yaml)
Effettivamente anche io ricordo che funzionano.

@serucci puoi verificare la tua configurazione con quella di @newtoni85 ?

Grazie a tutti 👍

**Comment by serucci** [comment]
questo è il mio yaml ,al volo vedo solo la nomenclatura nei register_component e nei binary delle aree ,sono numerate da 0 a 7. Nel mio sono 0-7 nei register_component e nei binary 1-8 , ma anche mettendoli uguali non cambia il risultato...altro non vedo


```
esphome:
  name: espkyogatebox
  comment: Alarm System Serial to HA controller
  platform: ESP8266
  board: d1_mini
  includes:
    - EspkyogateBoxOk/bentel_kyo32.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret hotspot_wifi_ssid
    password: !secret hotspot_wifi_password

captive_portal:

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
  
uart:
  id: uart_bus
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  
switch:
  - platform: safe_mode
    name: "ESPKyoGate (Safe Mode)"

binary_sensor:
  - platform: custom
    lambda: |-
      auto kyo32 = new Bentel_Kyo32(id(uart_bus));
      App.register_component(kyo32);
      return {
        kyo32->kyo_comunication,
        kyo32->stato_sirena,
        kyo32->warn_mancanza_rete,
        kyo32->sabotaggio_zona, 
        kyo32->sabotaggio_sistema,
        kyo32->warn_scomparsa_bpi,
        kyo32->warn_fusibile,
        kyo32->warn_batteria_bassa,
        kyo32->warn_guasto_linea_telefonica,
        kyo32->warn_codici_default,
        kyo32->warn_wireless,
        kyo32->sabotaggio_bpi,
        kyo32->sabotaggio_jam,
        kyo32->sabotaggio_wireless,
        kyo32->sabotaggio_chiave_falsa,
        
        &kyo32->zona[0],
        &kyo32->zona[1],
        &kyo32->zona[2],
        &kyo32->zona[3],
        &kyo32->zona[4],
        &kyo32->zona[5],
        &kyo32->zona[6],
        &kyo32->zona[7],
        &kyo32->zona[8],
        &kyo32->zona[9],
        &kyo32->zona[10],
        &kyo32->zona[11],
        &kyo32->zona[12],
        &kyo32->zona[13],
        &kyo32->zona[14],
        &kyo32->zona[15],
        
        &kyo32->zona_sabotaggio[0],
        &kyo32->zona_sabotaggio[1],
        &kyo32->zona_sabotaggio[2],
        &kyo32->zona_sabotaggio[3],
        &kyo32->zona_sabotaggio[4],
        &kyo32->zona_sabotaggio[5],
        &kyo32->zona_sabotaggio[6],
        &kyo32->zona_sabotaggio[7],
       	&kyo32->zona_sabotaggio[8],
        &kyo32->zona_sabotaggio[9],
        &kyo32->zona_sabotaggio[10],
        &kyo32->zona_sabotaggio[11],
        &kyo32->zona_sabotaggio[12],
        &kyo32->zona_sabotaggio[13],
        &kyo32->zona_sabotaggio[14],
        &kyo32->zona_sabotaggio[15],
        
      	&kyo32->zona_esclusa[0],
        &kyo32->zona_esclusa[1],
        &kyo32->zona_esclusa[2],
        &kyo32->zona_esclusa[3],
        &kyo32->zona_esclusa[4],
        &kyo32->zona_esclusa[5],
        &kyo32->zona_esclusa[6],
        &kyo32->zona_esclusa[7],
        &kyo32->zona_esclusa[8],
        &kyo32->zona_esclusa[9],
        &kyo32->zona_esclusa[10],
        &kyo32->zona_esclusa[11],
        &kyo32->zona_esclusa[12],
        &kyo32->zona_esclusa[13],
        &kyo32->zona_esclusa[14],
        &kyo32->zona_esclusa[15],
       
       	&kyo32->memoria_allarme_zona[0],
        &kyo32->memoria_allarme_zona[1],
        &kyo32->memoria_allarme_zona[2],
        &kyo32->memoria_allarme_zona[3],
        &kyo32->memoria_allarme_zona[4],
        &kyo32->memoria_allarme_zona[5],
        &kyo32->memoria_allarme_zona[6],
        &kyo32->memoria_allarme_zona[7],
        &kyo32->memoria_allarme_zona[8],
        &kyo32->memoria_allarme_zona[9],
        &kyo32->memoria_allarme_zona[10],
        &kyo32->memoria_allarme_zona[11],
        &kyo32->memoria_allarme_zona[12],
        &kyo32->memoria_allarme_zona[13],
        &kyo32->memoria_allarme_zona[14],
        &kyo32->memoria_allarme_zona[15],
        
        &kyo32->memoria_sabotaggio_zona[0],
        &kyo32->memoria_sabotaggio_zona[1],
        &kyo32->memoria_sabotaggio_zona[2],
        &kyo32->memoria_sabotaggio_zona[3],
        &kyo32->memoria_sabotaggio_zona[4],
        &kyo32->memoria_sabotaggio_zona[5],
        &kyo32->memoria_sabotaggio_zona[6],
        &kyo32->memoria_sabotaggio_zona[7],
        &kyo32->memoria_sabotaggio_zona[8],
        &kyo32->memoria_sabotaggio_zona[9],
        &kyo32->memoria_sabotaggio_zona[10],
        &kyo32->memoria_sabotaggio_zona[11],
        &kyo32->memoria_sabotaggio_zona[12],
        &kyo32->memoria_sabotaggio_zona[13],
        &kyo32->memoria_sabotaggio_zona[14],
        &kyo32->memoria_sabotaggio_zona[15],
        
        &kyo32->allarme_area[0],
        &kyo32->allarme_area[1],
        &kyo32->allarme_area[2],
        &kyo32->allarme_area[3],
        &kyo32->allarme_area[4],
        &kyo32->allarme_area[5],
        &kyo32->allarme_area[6],
        &kyo32->allarme_area[7],
        
        &kyo32->inserimento_totale_area[0],
        &kyo32->inserimento_totale_area[1],
        &kyo32->inserimento_totale_area[2],
        &kyo32->inserimento_totale_area[3],
        &kyo32->inserimento_totale_area[4],
        &kyo32->inserimento_totale_area[5],
        &kyo32->inserimento_totale_area[6],
        &kyo32->inserimento_totale_area[7],
        
        &kyo32->inserimento_parziale_area[0],
        &kyo32->inserimento_parziale_area[1],
        &kyo32->inserimento_parziale_area[2],
        &kyo32->inserimento_parziale_area[3],
        &kyo32->inserimento_parziale_area[4],
        &kyo32->inserimento_parziale_area[5],
        &kyo32->inserimento_parziale_area[6],
        &kyo32->inserimento_parziale_area[7],
        
        &kyo32->inserimento_parziale_ritardo_0_area[0],
        &kyo32->inserimento_parziale_ritardo_0_area[1],
        &kyo32->inserimento_parziale_ritardo_0_area[2],
        &kyo32->inserimento_parziale_ritardo_0_area[3],
        &kyo32->inserimento_parziale_ritardo_0_area[4],
        &kyo32->inserimento_parziale_ritardo_0_area[5],
        &kyo32->inserimento_parziale_ritardo_0_area[6],
        &kyo32->inserimento_parziale_ritardo_0_area[7],
        
        &kyo32->disinserita_area[0],
        &kyo32->disinserita_area[1],
        &kyo32->disinserita_area[2],
        &kyo32->disinserita_area[3],
        &kyo32->disinserita_area[4],
        &kyo32->disinserita_area[5],
        &kyo32->disinserita_area[6],
        &kyo32->disinserita_area[7],
        
        &kyo32->stato_uscita[0],
        &kyo32->stato_uscita[1],
        &kyo32->stato_uscita[2],
        &kyo32->stato_uscita[3],
        &kyo32->stato_uscita[4],
      };
    binary_sensors:
      - id: kyo_comunication
        name: "Comunicazione Centrale"
      - id: stato_sirena
        name: "Stato Sirena"
      - id: warn_mancanza_rete
        name: "Mancanza Rete"
      - id: sabotaggio_zona
        name: "Sabotaggio Zona"
      - id: sabotaggio_sistema
        name: "Sabotaggio Sistema"
      - id: warn_scomparsa_bpi
        name: "Scomparsa BPI"
      - id: warn_fusibile
        name: "Fusibile"
      - id: warn_batteria_bassa
        name: "Batteria Bassa"
      - id: warn_guasto_linea_telefonica
        name: "Guasto Linea Telefonica"
      - id: warn_codici_default
        name: "Codici Default"
      - id: warn_wireless
        name: "Wireless"
      - id: sabotaggio_bpi
        name: "Sabotaggio BPI"
      - id: sabotaggio_jam
        name: "Sabotaggio Jam"
      - id: sabotaggio_wireless
        name: "Sabotaggio wireless"
      - id: sabotaggio_chiave_falsa
        name: "Sabotaggio Chiave Falsa"

      - id: zona_1
        name: "TapparellaLetto"
        device_class: "window"
      - id: zona_2
        name: "FinestraLetto"
        device_class: "door"
      - id: zona_3
        name: "TapparellaBagno"
        device_class: "window"
      - id: zona_4
        name: "TapparellaCucina"
        device_class: "window"
      - id: zona_5
        name: "FinestraBagno"
        device_class: "door"
      - id: zona_6
        name: "VolumetrIngresso"
        device_class: "motion"
      - id: zona_7
        name: "VolumetrFrancy"
        device_class: "motion"
      - id: zona_8
        name: "Free"
        device_class: "motion"  
      - id: zona_9
        name: "FinestreTinello"
        device_class: "door"
      - id: zona_10
        name: "TapparelleTinello"
        device_class: "window"
      - id: zona_11
        name: "MagnetPortaBlind"
        device_class: "door"
      - id: zona_12
        name: "FinestreFrancy"
        device_class: "door"
      - id: zona_13
        name: "TapparelleFrancy"
        device_class: "window"
      - id: zona_14
        name: "VolumTinello"
        device_class: "motion"
      - id: zona_15
        name: "MicroPortaBli"
        device_class: "door"
      - id: zona_16
        name: "InerzialePortaBli"
        device_class: "door"  
      
      - id: zona_1_sabotaggio
        name: "SabotTapparellaLetto"
      - id: zona_2_sabotaggio
        name: "SabotFinestraLetto"
      - id: zona_3_sabotaggio
        name: "SabotTapparellaBagno"
      - id: zona_4_sabotaggio
        name: "SabotTapparellaCucina"
      - id: zona_5_sabotaggio
        name: "SabotFinestraBagno"
      - id: zona_6_sabotaggio
        name: "SabotVolumetrIngresso"
      - id: zona_7_sabotaggio
        name: "SabotVolumetrFrancy"
      - id: zona_8_sabotaggio
        name: "SabotLibera"  
      - id: zona_9_sabotaggio
        name: "SabotFinestreTinello"   
      - id: zona_10_sabotaggio
        name: "SabotTapparelleTinello"
      - id: zona_11_sabotaggio
        name: "SabotMagnetPortaBlind"
      - id: zona_12_sabotaggio
        name: "SabotFinestreFrancy"
      - id: zona_13_sabotaggio
        name: "SabotTapparelleFrancy"
      - id: zona_14_sabotaggio
        name: "SabotVolumTinello"
      - id: zona_15_sabotaggio
        name: "SabotMicroPortaBli"
      - id: zona_16_sabotaggio
        name: "SabotInerzialePortaBli"  
              
      - id: zona_esclusa_1
        name: "Escl. TapparellaLetto"
      - id: zona_esclusa_2
        name: "Escl. FinestraLetto"
      - id: zona_esclusa_3
        name: "Escl. TapparellaBagno"
      - id: zona_esclusa_4
        name: "Escl. TapparellaCucina"
      - id: zona_esclusa_5
        name: "Escl. FinestraBagno"
      - id: zona_esclusa_6
        name: "Escl. VolumetrIngresso"
      - id: zona_esclusa_7
        name: "Escl. VolumetrFrancy"
      - id: zona_esclusa_8
        name: "Escl. Free"  
      - id: zona_esclusa_9
        name: "Escl. FinestreTinello"  
      - id: zona_esclusa_10
        name: "Escl. TapparelleTinello"
      - id: zona_esclusa_11
        name: "Escl. MagnetPortaBlind"
      - id: zona_esclusa_12
        name: "Escl. FinestreFrancy"
      - id: zona_esclusa_13
        name: "Escl. TapparelleFrancy"
      - id: zona_esclusa_14
        name: "Escl. VolumTinello"
      - id: zona_esclusa_15
        name: "Escl. MicroPortaBli"
      - id: zona_esclusa_16
        name: "Escl. InerzialePortaBli"  
                
      - id: memoria_allarme_zona_1
        name: "Mem. Allarme TapparellaLetto"
      - id: memoria_allarme_zona_2
        name: "Mem. Allarme FinestraLetto"
      - id: memoria_allarme_zona_3
        name: "Mem. Allarme TapparellaBagno"
      - id: memoria_allarme_zona_4
        name: "Mem. Allarme TapparellaCucina"
      - id: memoria_allarme_zona_5
        name: "Mem. Allarme FinestraBagno"
      - id: memoria_allarme_zona_6
        name: "Mem. Allarme VolumetrIngresso"
      - id: memoria_allarme_zona_7
        name: "Mem. Allarme VolumetrFrancy"
      - id: memoria_allarme_zona_8
        name: "Mem. Allarme Free"  
      - id: memoria_allarme_zona_9
        name: "Mem. Allarme FinestreTinello"
      - id: memoria_allarme_zona_10
        name: "Mem. Allarme TapparelleTinello"
      - id: memoria_allarme_zona_11
        name: "Mem. Allarme MagnetPortaBlind"
      - id: memoria_allarme_zona_12
        name: "Mem. Allarme FinestreFrancy"
      - id: memoria_Allarme_zona_13
        name: "Mem. Allarme TapparelleFrancy"
      - id: memoria_allarme_zona_14
        name: "Mem. Allarme VolumetrTinello"
      - id: memoria_allarme_zona_15
        name: "Mem. Allarme MicroPortaBli"
      - id: memoria_allarme_zona_16
        name: "Mem. Allarme InerzialePortaBli"  
      
      - id: memoria_sabotaggio_zona_1
        name: "Mem. Sabotaggio TapparellaLetto"
      - id: memoria_sabotaggio_zona_2
        name: "Mem. Sabotaggio FinestraLetto"
      - id: memoria_sabotaggio_zona_3
        name: "Mem. Sabotaggio TapparellaBagno"
      - id: memoria_sabotaggio_zona_4
        name: "Mem. Sabotaggio TapparellaCucina"
      - id: memoria_sabotaggio_zona_5
        name: "Mem. Sabotaggio FinestraBagno"
      - id: memoria_sabotaggio_zona_6
        name: "Mem. Sabotaggio VolumetrIngresso"
      - id: memoria_sabotaggio_zona_7
        name: "Mem. Sabotaggio VolumetrFrancy"
      - id: memoria_sabotaggio_zona_8
        name: "Mem. Sabotaggio Free"  
      - id: memoria_sabotaggio_zona_9
        name: "Mem. Sabotaggio FinestreTinello"
      - id: memoria_sabotaggio_zona_10
        name: "Mem. Sabotaggio TapparelleTinello"
      - id: memoria_sabotaggio_zona_11
        name: "Mem. Sabotaggio MagnetPortaBlind"
      - id: memoria_sabotaggio_zona_12
        name: "Mem. Sabotaggio FinestreFrancy"
      - id: memoria_sabotaggio_zona_13
        name: "Mem. Sabotaggio TapparelleFrancy"
      - id: memoria_sabotaggio_zona_14
        name: "Mem. Sabotaggio VolumetrTinello"
      - id: memoria_sabotaggio_zona_15
        name: "Mem. Sabotaggio MicroPortaBli"
      - id: memoria_sabotaggio_zona_16
        name: "Mem. Sabotaggio InerzialePortaBli"  
      
      - id: allarme_area_1
        name: "AllarmeAreaTapparCortile"
      - id: allarme_area_2
        name: "AllarmeAreaFinestreCortile"
      - id: allarme_area_3
        name: "AllarmeAreaVolumetricoTinello"
      - id: allarme_area_4
        name: "AllarmeAreaTapparelleStrada"
      - id: allarme_area_5
        name: "AllarmeAreaFinestreStrada"
      - id: allarme_area_6
        name: "AllarmeAreaVolumetricoFrancy"
      - id: allarme_area_7
        name: "AllarmeAreaVolumetricoIngresso"
      - id: allarme_area_8
        name: "AllarmeAreaPortaBlindata"    

      - id: inserimento_totale_area_1
        name: "Ins. Totale TapparCortile"
      - id: inserimento_totale_area_2
        name: "Ins. Totale FinestreCortile"
      - id: inserimento_totale_area_3
        name: "Ins. Totale VolumetricoTinello"
      - id: inserimento_totale_area_4
        name: "Ins. Totale TapparelleStrada"
      - id: inserimento_totale_area_5
        name: "Ins. Totale FinestreStrada"
      - id: inserimento_totale_area_6
        name: "Ins. Totale VolumetricoFrancy"
      - id: inserimento_totale_area_7
        name: "Ins. Totale VolumetricoIngresso"
      - id: inserimento_totale_area_8
        name: "Ins. Totale PortaBlindata"    

      - id: inserimento_parziale_area_1
        name: "Ins. Parziale TapparCortile"
      - id: inserimento_parziale_area_2
        name: "Ins. Parziale FinestreCortile"
      - id: inserimento_parziale_area_3
        name: "Ins. Parziale VolumetricoTinello"
      - id: inserimento_parziale_area_4
        name: "Ins. Parziale TapparelleStrada" 
      - id: inserimento_parziale_area_5
        name: "Ins. Parziale FinestreStrada"
      - id: inserimento_parziale_area_6
        name: "Ins. Parziale VolumetricoFrancy"
      - id: inserimento_parziale_area_7
        name: "Ins. Parziale VolumetricoIngresso"
      - id: inserimento_parziale_area_8
        name: "Ins. Parziale PortaBlindata"    

      - id: inserimento_parziale_ritardo_0_area_1
        name: "Ins. Parziale Ritardo 0 TapparCortile"
      - id: inserimento_parziale_ritardo_0_area_2
        name: "Ins. Parziale Ritardo 0 FinestreCortile"
      - id: inserimento_parziale_ritardo_0_area_3
        name: "Ins. Parziale Ritardo 0 VolumetricoTinello"
      - id: inserimento_parziale_ritardo_0_area_4
        name: "Ins. Parziale Ritardo 0 TapparelleStrada"
      - id: inserimento_parziale_ritardo_0_area_5
        name: "Ins. Parziale Ritardo 0 FinestreStrada"
      - id: inserimento_parziale_ritardo_0_area_6
        name: "Ins. Parziale Ritardo 0 VolumetricoFrancy"
      - id: inserimento_parziale_ritardo_0_area_7
        name: "Ins. Parziale Ritardo 0 VolumetricoIngresso"
      - id: inserimento_parziale_ritardo_0_area_8
        name: "Ins. Parziale Ritardo 0 PortaBlindata"

      - id: disinserita_area_1
        name: "Disins. TapparCortile"
      - id: disinserita_area_2
        name: "Disins. FinestreCortile"
      - id: disinserita_area_3
        name: "Disins. VolumetricoTinello"
      - id: disinserita_area_4
        name: "Disins. TapparelleStrada"
      - id: disinserita_area_5
        name: "Disins. FinestreStrada"
      - id: disinserita_area_6
        name: "Disins. VolumetricoFrancy"
      - id: disinserita_area_7
        name: "Disins. VolumetricoIngresso"
      - id: disinserita_area_8
        name: "Disins. PortaBlindata"    

      - id: stato_uscita_1
        name: "Stato Uscita 1"
      - id: stato_uscita_2
        name: "Stato Uscita 2"
      - id: stato_uscita_3
        name: "Stato Uscita 3"
      - id: stato_uscita_4
        name: "Stato Uscita 4"
      - id: stato_uscita_5
        name: "Stato Uscita 5"

```

**Comment by lorenzo-deluca** [comment]
Scusa, che modulo usi tu? Dalla configurazione mi sembra di capire un esp8266.
Perché vedo che hai configurato molti sensori e più utenti mi hanno segnalato che il "povero" esp8266 fa fatica a gestire molti sensori.

Eventualmente se non hai un ESP32 o superiore puoi provare a fare una configurazione in cui mappi solo i sensori dell'allarme area?


Grazie

**Comment by newtoni85** [comment]
> Scusa, che modulo usi tu? Dalla configurazione mi sembra di capire un esp8266.
> Perché vedo che hai configurato molti sensori e più utenti mi hanno segnalato che il "povero" esp8266 fa fatica a gestire molti sensori.
> 
> Eventualmente se non hai un ESP32 o superiore puoi provare a fare una configurazione in cui mappi solo i sensori dell'allarme area?
> 
> 
> Grazie 

Anche io se posso essere utile ho dovuto fare con ESP32 perché con 8266 mi dava problemi di collegamento.

**Comment by serucci** [comment]
> Scusa, che modulo usi tu? Dalla configurazione mi sembra di capire un esp8266. Perché vedo che hai configurato molti sensori e più utenti mi hanno segnalato che il "povero" esp8266 fa fatica a gestire molti sensori.
> 
> Eventualmente se non hai un ESP32 o superiore puoi provare a fare una configurazione in cui mappi solo i sensori dell'allarme area?
> 
> Grazie
Uso un ESP8266 e i vari sensori , 15 zone, sono raggruppati/divisi per fare intervenire le varie aree ,8 .
Comunque si ,posso provare a ridurre il numero  di sensori e posso anche provare con un  ESP32

**Comment by lorenzo-deluca** [comment]
E' stato risolto il problema con l'ultima versione di firmware e aggiornamento a ESP32?

**Comment by serucci** [comment]
No ,non ho risolto ne con l'ultima versione del fw ne riducendo il numero
dei sensori...mi rimane solo l'uso del ESP32

Il giorno lun 10 giu 2024 alle ore 11:44 Lorenzo ***@***.***>
ha scritto:
