### ISSUE TITLE
Impossibilità ad effettuare l'OTA

### ISSUE THREAD

**Issue by amastrogiacomo1968** [lorenzo-deluca/espkyogate#58]
Ho appena aggiornarnato ESPHome all'ultima versione 2024.6.1, quando vorrei aggiornare il mio esp ho questo errore

`INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/antifurto-esp32.yaml...
Failed config

At least one platform must be specified for 'ota'; add 'platform: esphome' for original OTA functionality`.

Mi sono "perso" qualcosa da fare?

Grazie in anticipo

**Comment by lorenzo-deluca** [comment]
Ciao, sta scritto nelle breaking change di esphome [https://next.esphome.io/changelog/2024.6.0.html#ota-platforms](https://next.esphome.io/changelog/2024.6.0.html#ota-platforms)

Comunque aggiorno il file di configurazione di esempio.

**Comment by amastrogiacomo1968** [comment]
Ecco me lo ero perso, grazie
